export const FONDFONT_SCENE = {
  en: { owned: 'Your font file', profile: 'Profile created', install: 'Settings · Install', library: 'iOS system font library', onDevice: 'On this iPhone or iPad', alt: 'Conceptual installation sequence: an owned font file is installed through Settings into the iOS font library, then the same typeface is selected in Pages and Keynote documents. Three real font families demonstrate variety.' },
  'zh-hans': { owned: '你的字体文件', profile: '描述文件已生成', install: '设置 · 安装', library: 'iOS 系统字体库', onDevice: '在这台 iPhone 或 iPad 上', alt: '概念演示：自有字体文件经设置安装进 iOS 系统字体库，随后同一字体用于 Pages 文稿和 Keynote 幻灯片。三种真实书体依次展示。' },
  'zh-hant': { owned: '你的字體檔案', profile: '描述檔已產生', install: '設定 · 安裝', library: 'iOS 系統字體庫', onDevice: '在這台 iPhone 或 iPad 上', alt: '概念示範：自有字體檔案經設定安裝進 iOS 系統字體庫，隨後同一字體用於 Pages 文件與 Keynote 幻燈片。三種真實書體依次展示。' },
  ja: { owned: 'あなたのフォントファイル', profile: 'プロファイルを作成', install: '設定 · インストール', library: 'iOS フォントライブラリ', onDevice: 'この iPhone または iPad で', alt: '概念図：所有するフォントを設定から iOS フォントライブラリにインストールし、同じ書体を Pages と Keynote の書類で選択します。実際の3書体が順に登場します。' },
  ko: { owned: '내 폰트 파일', profile: '프로파일 생성', install: '설정 · 설치', library: 'iOS 시스템 폰트 보관함', onDevice: '이 iPhone 또는 iPad에서', alt: '개념 시연: 소유한 폰트를 설정에서 iOS 폰트 보관함에 설치한 뒤 같은 서체를 Pages와 Keynote 문서에 선택합니다. 실제 세 가지 서체가 차례로 표시됩니다.' },
  fr: { owned: 'Votre fichier de police', profile: 'Profil créé', install: 'Réglages · Installer', library: 'Bibliothèque de polices iOS', onDevice: 'Sur cet iPhone ou iPad', alt: 'Démonstration conceptuelle : une police personnelle est installée via Réglages dans la bibliothèque iOS, puis sélectionnée dans des documents Pages et Keynote. Trois véritables familles illustrent la diversité.' },
  de: { owned: 'Deine Schriftdatei', profile: 'Profil erstellt', install: 'Einstellungen · Installieren', library: 'iOS-Systemschriftbibliothek', onDevice: 'Auf diesem iPhone oder iPad', alt: 'Konzeptdarstellung: Eine eigene Schrift wird über Einstellungen in die iOS-Schriftbibliothek installiert und anschließend in Pages- und Keynote-Dokumenten ausgewählt. Drei echte Schriftfamilien zeigen die Vielfalt.' },
};
