// Generated by scripts/gen-yiyan-i18n.mjs — do not edit by hand.
export const YIYAN_LOCALES = {
  "": {
    "htmlLang": "zh-Hans",
    "title": "绎言 YiYan — 地道英语，边蹬边学",
    "description": "自动捕捉你在 Pi、Claude Code 或 Codex 里的输入，给出更自然的英语表达，再讲清楚为什么这样说。Mac 上积累，通过 iCloud 同步到 iPhone。",
    "canonical": "https://lazyapps.com/yiyan/",
    "ogTitle": "绎言 YiYan — 地道英语，边蹬边学",
    "ogDesc": "自动捕捉你在 Pi、Claude Code 或 Codex 里的输入，给出更自然的英语表达，再讲清楚为什么这样说。",
    "ogUrl": "https://lazyapps.com/yiyan/",
    "navAria": "主导航",
    "homeAria": "首页",
    "appTitle": "<span class=\"zh\">绎言</span>",
    "appTitleAttrs": "",
    "loaderLogo": "YIYAN",
    "localeNow": "简体中文",
    "selectAria": "切换语言",
    "selectedUrl": "/yiyan/",
    "h1": "<span class=\"zh\">地道英语，边蹬边学</span>",
    "sub": "自动捕捉你在 Pi、Claude Code 或 Codex 里的输入，给出更自然的英语表达，再讲清楚为什么这样说。在 Mac 上积累，通过 iCloud 同步到 iPhone，离开电脑也能继续复习。",
    "cta": [
      "下载 Mac 版",
      "iPhone 公开测试版",
      "查看更新记录"
    ],
    "trust": [
      "原请求照常发送",
      "无需另配模型或 API",
      "学习记录按日期整理"
    ],
    "cssTrust": "cjk",
    "shotAltMain": "绎言在 macOS 上的学习记录界面",
    "shotAltDetail": "一条绎言学习记录：原话、自然英语与重点笔记",
    "cards": [
      {
        "tag": "Pi · Claude Code · Codex",
        "tagLang": true,
        "title": "<span class=\"zh\">照常输入</span>",
        "p": "中文、英文、夹着说都行。你的原请求会先正常发送，不需要等待英语结果。"
      },
      {
        "tag": "当前工作不被打断",
        "tagLang": false,
        "title": "<span class=\"zh\">正事继续执行</span>",
        "p": "绎言不会改写或延迟当前请求，也不会把学习结果塞回正在进行的对话。"
      },
      {
        "tag": "无需另配模型或 API",
        "tagLang": false,
        "title": "<span class=\"zh\">后台补一版自然英语</span>",
        "p": "绎言让你刚才使用的工具处理同一句话，在保留原意和语气的前提下，给出一版更符合语境的表达。"
      },
      {
        "tag": "每天真实说过的话，就是练习",
        "tagLang": false,
        "title": "<span class=\"zh\">对照着学一点</span>",
        "p": "原话、自然英语和最多三条重点笔记放在一起：哪里变了，为什么更自然，下次还能怎么复用。"
      }
    ],
    "pair": {
      "headA": "拿你真的说过的话来学",
      "headB": "意思没变，说法顺了",
      "h2": "<span class=\"zh\">不是看不懂，是自己的话说不顺。</span>",
      "cellSrc": " <p class=\"mono\">你刚说的</p> <p class=\"line\">去掉装饰元素，突出重点，使用原装组件，不要自行发挥。</p> ",
      "cellOut": " <p class=\"mono\">英语里更自然的说法</p> <p class=\"line\" lang=\"en\" dir=\"ltr\">Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.</p> ",
      "whyHtml": " <p class=\"mono\">为什么这样说</p> <p class=\"line\">“keep the focus on…” 比直译 “highlight the key points” 更贴合设计反馈；“as-is” 表示按原样使用，“add your own spin” 则自然地表达了“自行发挥”。</p> <p class=\"mono\">下次可以直接用</p> <p class=\"pair__reuse\" lang=\"en\" dir=\"ltr\"><code>keep the focus on …</code><code>use … as-is</code><code>add your own spin</code></p> ",
      "srcLabel": "你刚说的",
      "srcLine": "去掉装饰元素，突出重点，使用原装组件，不要自行发挥。",
      "outLabel": "英语里更自然的说法",
      "outLine": "Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.",
      "ctaUrl": "",
      "ctaHtml": "",
      "whyLabel": "为什么这样说",
      "why": "“keep the focus on…” 比直译 “highlight the key points” 更贴合设计反馈；“as-is” 表示按原样使用，“add your own spin” 则自然地表达了“自行发挥”。",
      "reuseLabel": "下次可以直接用",
      "reuse": [
        "keep the focus on …",
        "use … as-is",
        "add your own spin"
      ]
    },
    "iphone": {
      "headA": "iPhone 公开测试版",
      "headB": "通过 iCloud 同步",
      "h2": "<span class=\"zh\">Mac 上积累，iPhone 上复习。</span>",
      "cellSrc": " <p class=\"line\">在 Mac 上完成的学习记录和收藏，会通过 iCloud 自动同步到 iPhone。离开电脑，也能按日期回看记录、听自然英语，随时复习收藏的内容。</p> <p><a data-hover href=\"https://testflight.apple.com/\"><span data-underline-link class=\"underline-link\">通过 TestFlight 体验</span> ↗</a></p> ",
      "cellOut": " <p class=\"line\">初次使用前，请先在 Mac 版绎言的“设置”中开启 iCloud 同步，并确保 Mac 和 iPhone 登录同一个 Apple 账户。iPhone 版目前仍在公开测试，功能和体验会继续完善。</p> ",
      "whyHtml": "",
      "srcLabel": "",
      "srcLine": "在 Mac 上完成的学习记录和收藏，会通过 iCloud 自动同步到 iPhone。离开电脑，也能按日期回看记录、听自然英语，随时复习收藏的内容。",
      "outLabel": "",
      "outLine": "初次使用前，请先在 Mac 版绎言的“设置”中开启 iCloud 同步，并确保 Mac 和 iPhone 登录同一个 Apple 账户。iPhone 版目前仍在公开测试，功能和体验会继续完善。",
      "ctaUrl": "https://testflight.apple.com/",
      "whyLabel": "",
      "why": "",
      "reuseLabel": "",
      "reuse": []
    },
    "bounds": {
      "headA": "边界说清楚",
      "headB": "只留下学习所需的内容",
      "h2": "<span class=\"zh\">只处理运行期间新增的用户消息。</span>",
      "note": "绎言不会安装进 Pi、Claude Code 或 Codex，也不会更改它们的设置。",
      "items": [
        {
          "q": "什么会成为学习记录？",
          "a": "有完整表达、确实值得学习的用户消息。中文会变成自然英语，英文会得到润色，中英混写会整理成完整英语。"
        },
        {
          "q": "什么会被略过？",
          "a": "只包含代码、路径、URL 或图片的消息；“好的”“继续”这类简短确认；以及 “commit and push” 这类简短仓库指令。"
        },
        {
          "q": "什么不会被保存？",
          "a": "AI 回复、工具输出、系统消息、会话 ID 和会话文件路径，都不会写进绎言的学习记录。"
        },
        {
          "q": "学习内容放在哪里？",
          "a": "首先保存在这台 Mac 上。只有在你开启 iCloud 同步后，已完成的学习记录与收藏才会存入你的个人 iCloud，并同步到 iPhone。疑似密钥会在进入学习任务和记录前先做高置信度脱敏。"
        },
        {
          "q": "需要再配置一套模型吗？",
          "a": "不需要。自然英语和学习笔记由你刚才使用的 Pi、Claude Code 或 Codex 生成；绎言不带自己的模型或 API 凭据。"
        },
        {
          "q": "和其他应用什么关系？",
          "a": "绎言是 lazyapps 出品的独立 Mac 应用。<a data-hover href=\"/privacy.zh.html\"><span data-underline-link class=\"underline-link\">隐私条款</span></a>"
        }
      ]
    },
    "next": {
      "imgAlt": "",
      "q": "<span class=\"zh\">从下一句话开始。</span>"
    },
    "brew": {
      "h3": "<span class=\"zh\">两行装好</span>",
      "label": "Homebrew",
      "install": "<span class=\"p\">$</span> brew tap cxa/yiyan https://github.com/cxa/yiyan\n<span class=\"p\">$</span> brew install --cask cxa/yiyan/yiyan",
      "p": "装好绎言，继续像平时一样使用 Pi、Claude Code 或 Codex。下一条有学习价值的新消息，会自动成为你的第一条学习记录。"
    },
    "footer": [
      "<a data-hover href=\"/\" lang=\"en\"><span data-underline-link class=\"underline-link\">lazyapps</span></a>",
      "<a data-hover href=\"mailto:lazyapps.feedback@gmail.com\"><span data-underline-link class=\"underline-link\">联系</span></a>",
      "<a data-hover href=\"/privacy.zh.html\"><span data-underline-link class=\"underline-link\">隐私</span></a>",
      "<a data-hover href=\"/privacy.en.html\" lang=\"en\"><span data-underline-link class=\"underline-link\">English</span></a>"
    ]
  },
  "ar": {
    "htmlLang": "ar",
    "htmlDir": "rtl",
    "title": "YiYan — إنجليزية طبيعية تتعلمها أثناء العمل",
    "description": "يلتقط YiYan ما تكتبه في Pi أو Claude Code أو Codex، ويعطيك صياغة إنجليزية أطبع، ويشرح لماذا تُقال هكذا. يتجمّع على الـMac ويتزامن إلى الـiPhone عبر iCloud.",
    "canonical": "https://lazyapps.com/yiyan/ar/",
    "ogTitle": "YiYan — إنجليزية طبيعية تتعلمها أثناء العمل",
    "ogDesc": "يلتقط YiYan ما تكتبه في Pi أو Claude Code أو Codex، ويعطيك صياغة إنجليزية أطبع، ويشرح لماذا تُقال هكذا.",
    "ogUrl": "https://lazyapps.com/yiyan/ar/",
    "navAria": "التنقل الرئيسي",
    "homeAria": "الرئيسية",
    "appTitle": "YiYan",
    "appTitleAttrs": " lang=\"en\"",
    "loaderLogo": "YIYAN",
    "localeNow": "العربية",
    "selectAria": "تغيير اللغة",
    "selectedUrl": "/yiyan/ar/",
    "h1": "إنجليزية طبيعية، تتعلمها أثناء العمل",
    "sub": "يلتقط YiYan ما تكتبه في Pi أو Claude Code أو Codex، ويعطيك صياغة إنجليزية أطبع، ويشرح لماذا تُقال هكذا. ما يتجمّع على الـMac يصل إلى الـiPhone عبر iCloud، فتواصل المراجعة بعيدًا عن المكتب.",
    "cta": [
      "تنزيل نسخة Mac",
      "نسخة iPhone التجريبية",
      "سجل التحديثات"
    ],
    "trust": [
      "طلبك يُرسل كما هو",
      "لا حاجة إلى نموذج أو API إضافي",
      "السجلات مرتبة بالتاريخ"
    ],
    "cssTrust": "cjk",
    "shotAltMain": "سجل التعلّم في YiYan على macOS",
    "shotAltDetail": "سجل واحد من YiYan: الجملة الأصلية والإنجليزية الطبيعية والملاحظات",
    "cards": [
      {
        "tag": "Pi · Claude Code · Codex",
        "tagLang": true,
        "title": "اكتب كما تفعل عادة",
        "p": "بلغتك أو بالإنجليزية أو بخلط الاثنين، كل ذلك مقبول. طلبك الأصلي يُرسل أولًا، فلا تنتظر الإنجليزية."
      },
      {
        "tag": "عملك الحالي لا يتوقف",
        "tagLang": false,
        "title": "المهم يمضي في طريقه",
        "p": "لا يعيد YiYan صياغة الطلب الذي أرسلته للتو ولا يؤخره، ولا يُعيد نتائجه إلى المحادثة الجارية."
      },
      {
        "tag": "لا نموذج ولا API إضافي",
        "tagLang": false,
        "title": "صياغة طبيعية في الخلفية",
        "p": "يمرّر YiYan الجملة نفسها إلى الأداة التي كنت تستخدمها، فيعود بصياغة تناسب السياق مع الحفاظ على المعنى والنبرة."
      },
      {
        "tag": "ما قلته فعلًا هو التمرين",
        "tagLang": false,
        "title": "تعلَّم بالمقارنة",
        "p": "جملتك الأصلية والإنجليزية الطبيعية وثلاث ملاحظات كحدّ أقصى، جنبًا إلى جنب: ما تغيّر، ولماذا صار أطبع، وكيف تعيد استخدامه."
      }
    ],
    "pair": {
      "headA": "تعلَّم من كلامك أنت",
      "headB": "المعنى كما هو، والصياغة أسلس",
      "h2": "الفهم سهل، والصعب أن تقولها بكلماتك.",
      "cellSrc": " <p class=\"mono\">ما كتبته للتو</p> <p class=\"line\">احذف العناصر الزخرفية، وأبرِز الأهم، واستخدم المكوّنات الأصلية كما هي، ولا تضِف من عندك.</p> ",
      "cellOut": " <p class=\"mono\">الأطبع في الإنجليزية</p> <p class=\"line\" lang=\"en\" dir=\"ltr\">Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.</p> ",
      "whyHtml": " <p class=\"mono\">لماذا تُقال هكذا</p> <p class=\"line\">عبارة «keep the focus on…» أليق بملاحظات التصميم من الترجمة الحرفية «highlight the key points»، و«as-is» تعني الاستخدام كما هو، و«add your own spin» هي التعبير الأصيل عن الإضافة من عندك.</p> <p class=\"mono\">جاهزة للاستخدام في المرة القادمة</p> <p class=\"pair__reuse\" lang=\"en\" dir=\"ltr\"><code>keep the focus on …</code><code>use … as-is</code><code>add your own spin</code></p> ",
      "srcLabel": "ما كتبته للتو",
      "srcLine": "احذف العناصر الزخرفية، وأبرِز الأهم، واستخدم المكوّنات الأصلية كما هي، ولا تضِف من عندك.",
      "outLabel": "الأطبع في الإنجليزية",
      "outLine": "Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.",
      "ctaUrl": "",
      "ctaHtml": "",
      "whyLabel": "لماذا تُقال هكذا",
      "why": "عبارة «keep the focus on…» أليق بملاحظات التصميم من الترجمة الحرفية «highlight the key points»، و«as-is» تعني الاستخدام كما هو، و«add your own spin» هي التعبير الأصيل عن الإضافة من عندك.",
      "reuseLabel": "جاهزة للاستخدام في المرة القادمة",
      "reuse": [
        "keep the focus on …",
        "use … as-is",
        "add your own spin"
      ]
    },
    "iphone": {
      "headA": "نسخة iPhone التجريبية",
      "headB": "مزامنة عبر iCloud",
      "h2": "اجمعها على الـMac، وراجعها على الـiPhone.",
      "cellSrc": " <p class=\"line\">السجلات والمفضّلات التي تُنجزها على الـMac تصل إلى الـiPhone تلقائيًا عبر iCloud. بعيدًا عن الحاسوب يمكنك تصفّحها بالتاريخ، والاستماع إلى الإنجليزية الطبيعية، ومراجعة ما حفظته.</p> <p><a data-hover href=\"https://testflight.apple.com/\"><span data-underline-link class=\"underline-link\">جرّبها عبر TestFlight</span> ↗</a></p> ",
      "cellOut": " <p class=\"line\">قبل الاستخدام الأول، شغّل مزامنة iCloud من إعدادات YiYan على الـMac، وتأكّد أن الـMac والـiPhone يستخدمان حساب Apple نفسه. نسخة الـiPhone لا تزال تجريبية عامة وتتحسّن باستمرار.</p> ",
      "whyHtml": "",
      "srcLabel": "",
      "srcLine": "السجلات والمفضّلات التي تُنجزها على الـMac تصل إلى الـiPhone تلقائيًا عبر iCloud. بعيدًا عن الحاسوب يمكنك تصفّحها بالتاريخ، والاستماع إلى الإنجليزية الطبيعية، ومراجعة ما حفظته.",
      "outLabel": "",
      "outLine": "قبل الاستخدام الأول، شغّل مزامنة iCloud من إعدادات YiYan على الـMac، وتأكّد أن الـMac والـiPhone يستخدمان حساب Apple نفسه. نسخة الـiPhone لا تزال تجريبية عامة وتتحسّن باستمرار.",
      "ctaUrl": "https://testflight.apple.com/",
      "whyLabel": "",
      "why": "",
      "reuseLabel": "",
      "reuse": []
    },
    "bounds": {
      "headA": "حدود مذكورة بوضوح",
      "headB": "لا يبقى إلا ما يلزم للتعلّم",
      "h2": "لا يتعامل إلا مع الرسائل الجديدة أثناء تشغيله.",
      "note": "لا يُثبَّت YiYan داخل Pi أو Claude Code أو Codex، ولا يغيّر إعداداتها.",
      "items": [
        {
          "q": "ما الذي يصير سجلًا؟",
          "a": "رسائلك التي تحمل معنى كاملًا ويُستفاد منها فعلًا. لغتك تصير إنجليزية طبيعية، والإنجليزية تُصقل، والمخلوط يُعاد كتابته إنجليزية كاملة."
        },
        {
          "q": "ما الذي يُتجاوز؟",
          "a": "الرسائل التي لا تحوي سوى كود أو مسارات أو روابط أو صور؛ والتأكيدات القصيرة مثل «تمام» أو «أكمل»؛ والأوامر القصيرة مثل «commit and push»."
        },
        {
          "q": "ما الذي لا يُحفظ أبدًا؟",
          "a": "ردود الذكاء الاصطناعي ومخرجات الأدوات ورسائل النظام ومعرّفات الجلسات ومسارات ملفاتها لا تدخل سجلات YiYan."
        },
        {
          "q": "وأين يُحفظ كل هذا؟",
          "a": "على هذا الـMac أولًا. وبعد تشغيل مزامنة iCloud فقط تنتقل السجلات المكتملة والمفضّلات إلى iCloud الخاص بك ثم إلى الـiPhone. وكل ما يُشبه المفاتيح السرّية يُحجب بثقة عالية قبل دخوله أي مهمة أو سجل."
        },
        {
          "q": "هل أحتاج نموذجًا آخر؟",
          "a": "لا. الإنجليزية الطبيعية والملاحظات يولّدها Pi أو Claude Code أو Codex الذي كنت تستخدمه؛ ولا يحمل YiYan نموذجًا ولا بيانات اعتماد API خاصة به."
        },
        {
          "q": "وما علاقته ببقية التطبيقات؟",
          "a": "‏YiYan تطبيق Mac مستقل من lazyapps. <a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">سياسة الخصوصية</span></a>"
        }
      ]
    },
    "next": {
      "imgAlt": "",
      "q": "ابدأ من جملتك القادمة."
    },
    "brew": {
      "h3": "سطران للتثبيت",
      "label": "Homebrew",
      "install": "<span class=\"p\">$</span> brew tap cxa/yiyan https://github.com/cxa/yiyan\n<span class=\"p\">$</span> brew install --cask cxa/yiyan/yiyan",
      "p": "ثبّت YiYan وواصل استخدام Pi أو Claude Code أو Codex كما كنت. أول رسالة جديدة تستحق التعلّم ستصير سجلك الأول."
    },
    "footer": [
      "<a data-hover href=\"/\" lang=\"en\"><span data-underline-link class=\"underline-link\">lazyapps</span></a>",
      "<a data-hover href=\"mailto:lazyapps.feedback@gmail.com\"><span data-underline-link class=\"underline-link\">اتصال</span></a>",
      "<a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">الخصوصية</span></a>",
      "<a data-hover href=\"/privacy.zh.html\" lang=\"zh\"><span data-underline-link class=\"underline-link\">中文</span></a>"
    ]
  },
  "de": {
    "htmlLang": "de",
    "title": "YiYan — Natürliches Englisch, nebenbei gelernt",
    "description": "YiYan greift auf, was du in Pi, Claude Code oder Codex schreibst, liefert eine natürlichere englische Fassung und erklärt, warum man es so sagt. Sammeln auf dem Mac, per iCloud zum iPhone.",
    "canonical": "https://lazyapps.com/yiyan/de/",
    "ogTitle": "YiYan — Natürliches Englisch, nebenbei gelernt",
    "ogDesc": "YiYan greift auf, was du in Pi, Claude Code oder Codex schreibst, liefert eine natürlichere englische Fassung und erklärt, warum man es so sagt.",
    "ogUrl": "https://lazyapps.com/yiyan/de/",
    "navAria": "Hauptnavigation",
    "homeAria": "Start",
    "appTitle": "YiYan",
    "appTitleAttrs": " lang=\"en\"",
    "loaderLogo": "YIYAN",
    "localeNow": "Deutsch",
    "selectAria": "Sprache wechseln",
    "selectedUrl": "/yiyan/de/",
    "h1": "Natürliches Englisch, nebenbei gelernt",
    "sub": "YiYan greift auf, was du in Pi, Claude Code oder Codex schreibst, liefert eine natürlichere englische Fassung und erklärt, warum man es so sagt. Was auf dem Mac zusammenkommt, landet per iCloud auf dem iPhone – Wiederholen geht auch ohne Schreibtisch.",
    "cta": [
      "Für Mac laden",
      "iPhone-Beta",
      "Änderungen ansehen"
    ],
    "trust": [
      "Deine Anfrage geht wie immer raus",
      "Kein zweites Modell, keine API",
      "Einträge nach Datum sortiert"
    ],
    "cssTrust": "latin",
    "shotAltMain": "Das Lernprotokoll von YiYan auf macOS",
    "shotAltDetail": "Ein YiYan-Eintrag: Originalsatz, natürliches Englisch und die wichtigsten Notizen",
    "cards": [
      {
        "tag": "Pi · Claude Code · Codex",
        "tagLang": true,
        "title": "Schreib wie immer",
        "p": "In deiner Sprache, auf Englisch oder gemischt – alles geht. Deine ursprüngliche Anfrage geht zuerst raus, du wartest nie auf das Englische."
      },
      {
        "tag": "Deine Arbeit wird nicht unterbrochen",
        "tagLang": false,
        "title": "Das Eigentliche läuft weiter",
        "p": "YiYan schreibt die gerade gesendete Anfrage nicht um und verzögert sie nicht, und schiebt seine Ergebnisse nie in das laufende Gespräch zurück."
      },
      {
        "tag": "Kein zweites Modell, keine API",
        "tagLang": false,
        "title": "Eine natürliche Fassung, im Hintergrund",
        "p": "YiYan gibt denselben Satz an das Werkzeug weiter, das du eben benutzt hast, und bekommt eine Formulierung zurück, die in den Kontext passt – Sinn und Ton bleiben."
      },
      {
        "tag": "Was du wirklich gesagt hast, ist die Übung",
        "tagLang": false,
        "title": "Lernen im Vergleich",
        "p": "Originalsatz, natürliches Englisch und höchstens drei Notizen stehen nebeneinander: was sich geändert hat, warum es natürlicher klingt, wie du es wiederverwendest."
      }
    ],
    "pair": {
      "headA": "Lerne an dem, was du wirklich geschrieben hast",
      "headB": "Der Sinn bleibt, die Formulierung wird rund",
      "h2": "Verstehen ist leicht. Es selbst sagen ist das Schwere.",
      "cellSrc": " <p class=\"mono\">Was du eben geschrieben hast</p> <p class=\"line\">Entferne die dekorativen Elemente, stelle das Wesentliche heraus, verwende die Original-Komponenten und improvisiere nicht.</p> ",
      "cellOut": " <p class=\"mono\">Natürlicher auf Englisch</p> <p class=\"line\" lang=\"en\" dir=\"ltr\">Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.</p> ",
      "whyHtml": " <p class=\"mono\">Warum man es so sagt</p> <p class=\"line\">„keep the focus on…“ trifft Design-Feedback besser als das wörtliche „highlight the key points“; „as-is“ heißt unverändert übernehmen, und „add your own spin“ ist die native Wendung für improvisieren.</p> <p class=\"mono\">Nächstes Mal direkt nutzen</p> <p class=\"pair__reuse\" lang=\"en\" dir=\"ltr\"><code>keep the focus on …</code><code>use … as-is</code><code>add your own spin</code></p> ",
      "srcLabel": "Was du eben geschrieben hast",
      "srcLine": "Entferne die dekorativen Elemente, stelle das Wesentliche heraus, verwende die Original-Komponenten und improvisiere nicht.",
      "outLabel": "Natürlicher auf Englisch",
      "outLine": "Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.",
      "ctaUrl": "",
      "ctaHtml": "",
      "whyLabel": "Warum man es so sagt",
      "why": "„keep the focus on…“ trifft Design-Feedback besser als das wörtliche „highlight the key points“; „as-is“ heißt unverändert übernehmen, und „add your own spin“ ist die native Wendung für improvisieren.",
      "reuseLabel": "Nächstes Mal direkt nutzen",
      "reuse": [
        "keep the focus on …",
        "use … as-is",
        "add your own spin"
      ]
    },
    "iphone": {
      "headA": "iPhone-Beta",
      "headB": "Über iCloud synchronisiert",
      "h2": "Auf dem Mac sammeln, auf dem iPhone wiederholen.",
      "cellSrc": " <p class=\"line\">Auf dem Mac fertiggestellte Einträge und Favoriten landen automatisch per iCloud auf dem iPhone. Auch ohne Rechner kannst du nach Datum blättern, das natürliche Englisch hören und Gespeichertes wiederholen.</p> <p><a data-hover href=\"https://testflight.apple.com/\"><span data-underline-link class=\"underline-link\">Über TestFlight ausprobieren</span> ↗</a></p> ",
      "cellOut": " <p class=\"line\">Aktiviere vor dem ersten Start die iCloud-Synchronisierung in den Einstellungen von YiYan für Mac und achte darauf, dass Mac und iPhone im selben Apple-Account angemeldet sind. Die iPhone-Fassung ist weiterhin eine öffentliche Beta.</p> ",
      "whyHtml": "",
      "srcLabel": "",
      "srcLine": "Auf dem Mac fertiggestellte Einträge und Favoriten landen automatisch per iCloud auf dem iPhone. Auch ohne Rechner kannst du nach Datum blättern, das natürliche Englisch hören und Gespeichertes wiederholen.",
      "outLabel": "",
      "outLine": "Aktiviere vor dem ersten Start die iCloud-Synchronisierung in den Einstellungen von YiYan für Mac und achte darauf, dass Mac und iPhone im selben Apple-Account angemeldet sind. Die iPhone-Fassung ist weiterhin eine öffentliche Beta.",
      "ctaUrl": "https://testflight.apple.com/",
      "whyLabel": "",
      "why": "",
      "reuseLabel": "",
      "reuse": []
    },
    "bounds": {
      "headA": "Grenzen, klar benannt",
      "headB": "Nur das, was zum Lernen nötig ist",
      "h2": "Nur neue Nachrichten, die du im laufenden Betrieb sendest.",
      "note": "YiYan installiert sich nicht in Pi, Claude Code oder Codex und ändert deren Einstellungen nie.",
      "items": [
        {
          "q": "Was wird zum Eintrag?",
          "a": "Deine Nachrichten, die etwas Ganzes sagen und aus denen sich wirklich lernen lässt. Deine Sprache wird zu natürlichem Englisch, Englisch wird geschliffen, Gemischtes wird zu vollständigem Englisch."
        },
        {
          "q": "Was wird übersprungen?",
          "a": "Nachrichten aus reinem Code, Pfaden, URLs oder Bildern; kurze Bestätigungen wie „ok“ oder „weiter“; und kurze Repository-Befehle wie „commit and push“."
        },
        {
          "q": "Was wird nie gespeichert?",
          "a": "KI-Antworten, Werkzeugausgaben, Systemmeldungen, Sitzungs-IDs und Pfade von Sitzungsdateien landen nie in einem YiYan-Eintrag."
        },
        {
          "q": "Wo liegt das alles?",
          "a": "Zuerst auf diesem Mac. Erst wenn du die iCloud-Synchronisierung einschaltest, gehen fertige Einträge und Favoriten in deine iCloud und auf das iPhone. Was wie ein Geheimnis aussieht, wird mit hoher Sicherheit maskiert, bevor es in eine Lernaufgabe oder einen Eintrag gelangt."
        },
        {
          "q": "Brauche ich ein weiteres Modell?",
          "a": "Nein. Das natürliche Englisch und die Notizen kommen von dem Pi, Claude Code oder Codex, das du eben benutzt hast; YiYan bringt kein eigenes Modell und keine API-Zugangsdaten mit."
        },
        {
          "q": "Wie hängt das mit dem Rest zusammen?",
          "a": "YiYan ist eine eigenständige Mac-App von lazyapps. <a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">Datenschutz</span></a>"
        }
      ]
    },
    "next": {
      "imgAlt": "",
      "q": "Fang mit deinem nächsten Satz an."
    },
    "brew": {
      "h3": "Zwei Zeilen, fertig",
      "label": "Homebrew",
      "install": "<span class=\"p\">$</span> brew tap cxa/yiyan https://github.com/cxa/yiyan\n<span class=\"p\">$</span> brew install --cask cxa/yiyan/yiyan",
      "p": "Installiere YiYan und nutze Pi, Claude Code oder Codex weiter wie bisher. Die nächste Nachricht, aus der sich etwas lernen lässt, wird dein erster Eintrag."
    },
    "footer": [
      "<a data-hover href=\"/\" lang=\"en\"><span data-underline-link class=\"underline-link\">lazyapps</span></a>",
      "<a data-hover href=\"mailto:lazyapps.feedback@gmail.com\"><span data-underline-link class=\"underline-link\">Kontakt</span></a>",
      "<a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">Datenschutz</span></a>",
      "<a data-hover href=\"/privacy.zh.html\" lang=\"zh\"><span data-underline-link class=\"underline-link\">中文</span></a>"
    ]
  },
  "en": {
    "htmlLang": "en",
    "title": "YiYan — Natural English, picked up as you go",
    "description": "YiYan quietly picks up what you type in Pi, Claude Code or Codex, gives you a more natural English version, and explains why it reads that way. Build it up on Mac, sync to iPhone over iCloud.",
    "canonical": "https://lazyapps.com/yiyan/en/",
    "ogTitle": "YiYan — Natural English, picked up as you go",
    "ogDesc": "YiYan quietly picks up what you type in Pi, Claude Code or Codex, gives you a more natural English version, and explains why it reads that way.",
    "ogUrl": "https://lazyapps.com/yiyan/en/",
    "navAria": "Main navigation",
    "homeAria": "Home",
    "appTitle": "YiYan",
    "appTitleAttrs": " lang=\"en\"",
    "loaderLogo": "YIYAN",
    "localeNow": "English",
    "selectAria": "Change language",
    "selectedUrl": "/yiyan/en/",
    "h1": "Natural English, picked up as you go",
    "sub": "YiYan quietly picks up what you type in Pi, Claude Code or Codex, gives you a more natural English version, and explains why it reads that way. Everything you collect on Mac syncs to iPhone over iCloud, so you can keep reviewing away from your desk.",
    "cta": [
      "Download for Mac",
      "iPhone public beta",
      "Release notes"
    ],
    "trust": [
      "Your request is sent as usual",
      "No extra model or API to set up",
      "Entries filed by date"
    ],
    "cssTrust": "latin",
    "shotAltMain": "The YiYan learning log on macOS",
    "shotAltDetail": "One YiYan entry: the original wording, the natural English, and the key notes",
    "cards": [
      {
        "tag": "Pi · Claude Code · Codex",
        "tagLang": true,
        "title": "Type as usual",
        "p": "Your own language, English, or a mix of both — all fine. Your original request goes out first, so you never wait on the English."
      },
      {
        "tag": "Your work is never interrupted",
        "tagLang": false,
        "title": "The real work keeps running",
        "p": "YiYan never rewrites or delays the request you just sent, and never pushes its results back into the conversation you are having."
      },
      {
        "tag": "No extra model or API",
        "tagLang": false,
        "title": "A natural version, in the background",
        "p": "YiYan hands the same sentence to the tool you were just using, and gets back wording that fits the context while keeping your meaning and tone."
      },
      {
        "tag": "What you really said is the practice",
        "tagLang": false,
        "title": "Learn from the comparison",
        "p": "Your original wording, the natural English and at most three notes sit side by side: what changed, why it reads better, and how to reuse it next time."
      }
    ],
    "pair": {
      "headA": "Learn from what you actually wrote",
      "headB": "Same meaning, smoother wording",
      "h2": "Understanding it is easy. Saying it your way is the hard part.",
      "cellSrc": " <p class=\"mono\">What you just wrote</p> <p class=\"line\">Delete the decoration elements, make the key points prominent, use the original components, and do not play by yourself.</p> ",
      "cellOut": " <p class=\"mono\">A more natural way to say it</p> <p class=\"line\" lang=\"en\" dir=\"ltr\">Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.</p> ",
      "whyHtml": " <p class=\"mono\">Why it reads that way</p> <p class=\"line\">“keep the focus on…” lands better in design feedback than a literal “highlight the key points”; “as-is” says use it exactly as shipped, and “add your own spin” is how a native speaker names improvising.</p> <p class=\"mono\">Reuse it next time</p> <p class=\"pair__reuse\" lang=\"en\" dir=\"ltr\"><code>keep the focus on …</code><code>use … as-is</code><code>add your own spin</code></p> ",
      "srcLabel": "What you just wrote",
      "srcLine": "Delete the decoration elements, make the key points prominent, use the original components, and do not play by yourself.",
      "outLabel": "A more natural way to say it",
      "outLine": "Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.",
      "ctaUrl": "",
      "ctaHtml": "",
      "whyLabel": "Why it reads that way",
      "why": "“keep the focus on…” lands better in design feedback than a literal “highlight the key points”; “as-is” says use it exactly as shipped, and “add your own spin” is how a native speaker names improvising.",
      "reuseLabel": "Reuse it next time",
      "reuse": [
        "keep the focus on …",
        "use … as-is",
        "add your own spin"
      ]
    },
    "iphone": {
      "headA": "iPhone public beta",
      "headB": "Synced over iCloud",
      "h2": "Build it up on Mac, review it on iPhone.",
      "cellSrc": " <p class=\"line\">Entries and favourites you finish on Mac sync to iPhone automatically over iCloud. Away from the computer you can still browse by date, listen to the natural English, and review anything you saved.</p> <p><a data-hover href=\"https://testflight.apple.com/\"><span data-underline-link class=\"underline-link\">Try it on TestFlight</span> ↗</a></p> ",
      "cellOut": " <p class=\"line\">Before your first run, turn on iCloud sync in Settings in YiYan for Mac, and make sure Mac and iPhone are signed in to the same Apple Account. The iPhone version is still a public beta and keeps improving.</p> ",
      "whyHtml": "",
      "srcLabel": "",
      "srcLine": "Entries and favourites you finish on Mac sync to iPhone automatically over iCloud. Away from the computer you can still browse by date, listen to the natural English, and review anything you saved.",
      "outLabel": "",
      "outLine": "Before your first run, turn on iCloud sync in Settings in YiYan for Mac, and make sure Mac and iPhone are signed in to the same Apple Account. The iPhone version is still a public beta and keeps improving.",
      "ctaUrl": "https://testflight.apple.com/",
      "whyLabel": "",
      "why": "",
      "reuseLabel": "",
      "reuse": []
    },
    "bounds": {
      "headA": "Boundaries, stated plainly",
      "headB": "Only what learning needs",
      "h2": "Only new messages you send while it is running.",
      "note": "YiYan does not install itself into Pi, Claude Code or Codex, and never changes their settings.",
      "items": [
        {
          "q": "What becomes an entry?",
          "a": "Messages of yours that say something whole and are genuinely worth learning from. Your own language becomes natural English, English gets polished, and a mix of the two is rewritten as complete English."
        },
        {
          "q": "What gets skipped?",
          "a": "Messages that are only code, paths, URLs or images; short confirmations like “ok” or “go on”; and short repository commands like “commit and push”."
        },
        {
          "q": "What is never stored?",
          "a": "AI replies, tool output, system messages, session IDs and session file paths never make it into a YiYan entry."
        },
        {
          "q": "Where does it live?",
          "a": "On this Mac first. Only after you turn on iCloud sync do finished entries and favourites go to your own iCloud and reach your iPhone. Anything that looks like a secret is redacted with high confidence before it enters a learning task or an entry."
        },
        {
          "q": "Do I need another model?",
          "a": "No. The natural English and the notes come from the Pi, Claude Code or Codex you were just using; YiYan ships no model and no API credentials of its own."
        },
        {
          "q": "How does it relate to the rest?",
          "a": "YiYan is a standalone Mac app from lazyapps. <a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">Privacy policy</span></a>"
        }
      ]
    },
    "next": {
      "imgAlt": "",
      "q": "Start with your next sentence."
    },
    "brew": {
      "h3": "Two lines to install",
      "label": "Homebrew",
      "install": "<span class=\"p\">$</span> brew tap cxa/yiyan https://github.com/cxa/yiyan\n<span class=\"p\">$</span> brew install --cask cxa/yiyan/yiyan",
      "p": "Install YiYan and keep using Pi, Claude Code or Codex exactly as before. The next message worth learning from becomes your first entry."
    },
    "footer": [
      "<a data-hover href=\"/\" lang=\"en\"><span data-underline-link class=\"underline-link\">lazyapps</span></a>",
      "<a data-hover href=\"mailto:lazyapps.feedback@gmail.com\"><span data-underline-link class=\"underline-link\">Contact</span></a>",
      "<a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">Privacy</span></a>",
      "<a data-hover href=\"/privacy.zh.html\" lang=\"zh\"><span data-underline-link class=\"underline-link\">中文</span></a>"
    ]
  },
  "es": {
    "htmlLang": "es",
    "title": "YiYan — Inglés natural, aprendido sobre la marcha",
    "description": "YiYan recoge lo que escribes en Pi, Claude Code o Codex, te da una versión en inglés más natural y explica por qué se dice así. Se acumula en el Mac y se sincroniza al iPhone por iCloud.",
    "canonical": "https://lazyapps.com/yiyan/es/",
    "ogTitle": "YiYan — Inglés natural, aprendido sobre la marcha",
    "ogDesc": "YiYan recoge lo que escribes en Pi, Claude Code o Codex, te da una versión en inglés más natural y explica por qué se dice así.",
    "ogUrl": "https://lazyapps.com/yiyan/es/",
    "navAria": "Navegación principal",
    "homeAria": "Inicio",
    "appTitle": "YiYan",
    "appTitleAttrs": " lang=\"en\"",
    "loaderLogo": "YIYAN",
    "localeNow": "Español",
    "selectAria": "Cambiar de idioma",
    "selectedUrl": "/yiyan/es/",
    "h1": "Inglés natural, aprendido sobre la marcha",
    "sub": "YiYan recoge lo que escribes en Pi, Claude Code o Codex, te da una versión en inglés más natural y explica por qué se dice así. Lo que reúnes en el Mac se sincroniza al iPhone por iCloud, para seguir repasando lejos del escritorio.",
    "cta": [
      "Descargar para Mac",
      "Beta pública para iPhone",
      "Notas de la versión"
    ],
    "trust": [
      "Tu petición se envía igual que siempre",
      "Sin otro modelo ni API que configurar",
      "Registros ordenados por fecha"
    ],
    "cssTrust": "latin",
    "shotAltMain": "El registro de aprendizaje de YiYan en macOS",
    "shotAltDetail": "Un registro de YiYan: la frase original, el inglés natural y las notas clave",
    "cards": [
      {
        "tag": "Pi · Claude Code · Codex",
        "tagLang": true,
        "title": "Escribe como siempre",
        "p": "En tu idioma, en inglés o mezclando los dos: todo vale. Tu petición original sale primero, así que nunca esperas por el inglés."
      },
      {
        "tag": "Tu trabajo no se interrumpe",
        "tagLang": false,
        "title": "Lo importante sigue su curso",
        "p": "YiYan no reescribe ni retrasa la petición que acabas de enviar, y nunca devuelve sus resultados a la conversación en marcha."
      },
      {
        "tag": "Sin otro modelo ni API",
        "tagLang": false,
        "title": "Una versión natural, en segundo plano",
        "p": "YiYan pasa la misma frase a la herramienta que acabas de usar y recibe una redacción que encaja en el contexto sin cambiar tu intención ni tu tono."
      },
      {
        "tag": "Lo que dijiste de verdad es la práctica",
        "tagLang": false,
        "title": "Aprende comparando",
        "p": "Tu frase original, el inglés natural y como máximo tres notas van juntos: qué cambió, por qué suena mejor y cómo reutilizarlo la próxima vez."
      }
    ],
    "pair": {
      "headA": "Aprende de lo que escribiste de verdad",
      "headB": "El sentido intacto, la forma más fluida",
      "h2": "Entenderlo es fácil; decirlo a tu manera es lo difícil.",
      "cellSrc": " <p class=\"mono\">Lo que acabas de escribir</p> <p class=\"line\">Quita los elementos decorativos, destaca lo importante, usa los componentes originales y no improvises.</p> ",
      "cellOut": " <p class=\"mono\">Cómo suena más natural en inglés</p> <p class=\"line\" lang=\"en\" dir=\"ltr\">Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.</p> ",
      "whyHtml": " <p class=\"mono\">Por qué se dice así</p> <p class=\"line\">«keep the focus on…» funciona mejor en una crítica de diseño que el literal «highlight the key points»; «as-is» significa usarlo tal como viene, y «add your own spin» es la forma nativa de decir improvisar.</p> <p class=\"mono\">Para usar la próxima vez</p> <p class=\"pair__reuse\" lang=\"en\" dir=\"ltr\"><code>keep the focus on …</code><code>use … as-is</code><code>add your own spin</code></p> ",
      "srcLabel": "Lo que acabas de escribir",
      "srcLine": "Quita los elementos decorativos, destaca lo importante, usa los componentes originales y no improvises.",
      "outLabel": "Cómo suena más natural en inglés",
      "outLine": "Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.",
      "ctaUrl": "",
      "ctaHtml": "",
      "whyLabel": "Por qué se dice así",
      "why": "«keep the focus on…» funciona mejor en una crítica de diseño que el literal «highlight the key points»; «as-is» significa usarlo tal como viene, y «add your own spin» es la forma nativa de decir improvisar.",
      "reuseLabel": "Para usar la próxima vez",
      "reuse": [
        "keep the focus on …",
        "use … as-is",
        "add your own spin"
      ]
    },
    "iphone": {
      "headA": "Beta pública para iPhone",
      "headB": "Sincronizado por iCloud",
      "h2": "Acumúlalo en el Mac, repásalo en el iPhone.",
      "cellSrc": " <p class=\"line\">Los registros y favoritos que terminas en el Mac llegan al iPhone automáticamente por iCloud. Lejos del ordenador puedes revisarlos por fecha, escuchar el inglés natural y repasar lo que guardaste.</p> <p><a data-hover href=\"https://testflight.apple.com/\"><span data-underline-link class=\"underline-link\">Pruébalo en TestFlight</span> ↗</a></p> ",
      "cellOut": " <p class=\"line\">Antes del primer uso, activa la sincronización con iCloud en los ajustes de YiYan para Mac y comprueba que Mac y iPhone usan la misma cuenta de Apple. La versión para iPhone sigue en beta pública y seguirá mejorando.</p> ",
      "whyHtml": "",
      "srcLabel": "",
      "srcLine": "Los registros y favoritos que terminas en el Mac llegan al iPhone automáticamente por iCloud. Lejos del ordenador puedes revisarlos por fecha, escuchar el inglés natural y repasar lo que guardaste.",
      "outLabel": "",
      "outLine": "Antes del primer uso, activa la sincronización con iCloud en los ajustes de YiYan para Mac y comprueba que Mac y iPhone usan la misma cuenta de Apple. La versión para iPhone sigue en beta pública y seguirá mejorando.",
      "ctaUrl": "https://testflight.apple.com/",
      "whyLabel": "",
      "why": "",
      "reuseLabel": "",
      "reuse": []
    },
    "bounds": {
      "headA": "Los límites, dichos claro",
      "headB": "Solo lo que el aprendizaje necesita",
      "h2": "Solo los mensajes nuevos que envías mientras está en marcha.",
      "note": "YiYan no se instala dentro de Pi, Claude Code ni Codex, y nunca cambia sus ajustes.",
      "items": [
        {
          "q": "¿Qué se convierte en registro?",
          "a": "Tus mensajes que dicen algo completo y de los que realmente se puede aprender. Tu idioma pasa a inglés natural, el inglés se pule y la mezcla de ambos se reescribe como inglés completo."
        },
        {
          "q": "¿Qué se omite?",
          "a": "Los mensajes que solo son código, rutas, URL o imágenes; confirmaciones cortas como «vale» o «sigue»; y órdenes breves de repositorio como «commit and push»."
        },
        {
          "q": "¿Qué no se guarda nunca?",
          "a": "Las respuestas de la IA, la salida de herramientas, los mensajes del sistema, los identificadores de sesión y las rutas de sus archivos nunca entran en un registro de YiYan."
        },
        {
          "q": "¿Dónde se guarda?",
          "a": "Primero en este Mac. Solo si activas la sincronización con iCloud, los registros terminados y los favoritos pasan a tu iCloud y llegan al iPhone. Todo lo que parezca una credencial se oculta con alta confianza antes de entrar en una tarea o un registro."
        },
        {
          "q": "¿Hace falta otro modelo?",
          "a": "No. El inglés natural y las notas los genera el Pi, Claude Code o Codex que acabas de usar; YiYan no trae modelo ni credenciales de API propias."
        },
        {
          "q": "¿Y su relación con lo demás?",
          "a": "YiYan es una app de Mac independiente de lazyapps. <a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">Política de privacidad</span></a>"
        }
      ]
    },
    "next": {
      "imgAlt": "",
      "q": "Empieza por tu próxima frase."
    },
    "brew": {
      "h3": "Dos líneas y listo",
      "label": "Homebrew",
      "install": "<span class=\"p\">$</span> brew tap cxa/yiyan https://github.com/cxa/yiyan\n<span class=\"p\">$</span> brew install --cask cxa/yiyan/yiyan",
      "p": "Instala YiYan y sigue usando Pi, Claude Code o Codex igual que antes. El próximo mensaje del que valga la pena aprender será tu primer registro."
    },
    "footer": [
      "<a data-hover href=\"/\" lang=\"en\"><span data-underline-link class=\"underline-link\">lazyapps</span></a>",
      "<a data-hover href=\"mailto:lazyapps.feedback@gmail.com\"><span data-underline-link class=\"underline-link\">Contacto</span></a>",
      "<a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">Privacidad</span></a>",
      "<a data-hover href=\"/privacy.zh.html\" lang=\"zh\"><span data-underline-link class=\"underline-link\">中文</span></a>"
    ]
  },
  "fr": {
    "htmlLang": "fr",
    "title": "YiYan — Un anglais naturel, appris en chemin",
    "description": "YiYan récupère ce que vous écrivez dans Pi, Claude Code ou Codex, en propose une version anglaise plus naturelle et explique pourquoi on le dit ainsi. Tout s accumule sur le Mac et se synchronise vers l iPhone via iCloud.",
    "canonical": "https://lazyapps.com/yiyan/fr/",
    "ogTitle": "YiYan — Un anglais naturel, appris en chemin",
    "ogDesc": "YiYan récupère ce que vous écrivez dans Pi, Claude Code ou Codex, en propose une version anglaise plus naturelle et explique pourquoi on le dit ainsi.",
    "ogUrl": "https://lazyapps.com/yiyan/fr/",
    "navAria": "Navigation principale",
    "homeAria": "Accueil",
    "appTitle": "YiYan",
    "appTitleAttrs": " lang=\"en\"",
    "loaderLogo": "YIYAN",
    "localeNow": "Français",
    "selectAria": "Changer de langue",
    "selectedUrl": "/yiyan/fr/",
    "h1": "Un anglais naturel, appris en chemin",
    "sub": "YiYan récupère ce que vous écrivez dans Pi, Claude Code ou Codex, en propose une version anglaise plus naturelle et explique pourquoi on le dit ainsi. Ce que vous accumulez sur le Mac rejoint l’iPhone via iCloud : la révision continue loin du bureau.",
    "cta": [
      "Télécharger pour Mac",
      "Bêta publique iPhone",
      "Notes de version"
    ],
    "trust": [
      "Votre requête part comme d’habitude",
      "Aucun modèle ni API à configurer",
      "Fiches classées par date"
    ],
    "cssTrust": "latin",
    "shotAltMain": "Le journal d’apprentissage de YiYan sur macOS",
    "shotAltDetail": "Une fiche YiYan : la phrase d’origine, l’anglais naturel et les notes clés",
    "cards": [
      {
        "tag": "Pi · Claude Code · Codex",
        "tagLang": true,
        "title": "Écrivez comme d’habitude",
        "p": "Dans votre langue, en anglais ou en mélangeant les deux : tout passe. Votre requête d’origine part en premier, vous n’attendez jamais l’anglais."
      },
      {
        "tag": "Votre travail n’est pas interrompu",
        "tagLang": false,
        "title": "L’essentiel continue de tourner",
        "p": "YiYan ne réécrit ni ne retarde la requête que vous venez d’envoyer, et ne renvoie jamais ses résultats dans la conversation en cours."
      },
      {
        "tag": "Aucun modèle ni API en plus",
        "tagLang": false,
        "title": "Une version naturelle, en arrière-plan",
        "p": "YiYan confie la même phrase à l’outil que vous veniez d’utiliser et récupère une formulation adaptée au contexte, sans toucher au sens ni au ton."
      },
      {
        "tag": "Ce que vous avez vraiment dit devient l’exercice",
        "tagLang": false,
        "title": "Apprenez par comparaison",
        "p": "La phrase d’origine, l’anglais naturel et trois notes au maximum côte à côte : ce qui a changé, pourquoi c’est plus naturel, comment le réutiliser."
      }
    ],
    "pair": {
      "headA": "Apprenez de ce que vous avez vraiment écrit",
      "headB": "Le sens intact, la formulation plus fluide",
      "h2": "Comprendre est facile ; le dire à votre façon, beaucoup moins.",
      "cellSrc": " <p class=\"mono\">Ce que vous venez d’écrire</p> <p class=\"line\">Supprime les éléments décoratifs, mets l’essentiel en avant, utilise les composants d’origine et n’improvise pas.</p> ",
      "cellOut": " <p class=\"mono\">La tournure plus naturelle en anglais</p> <p class=\"line\" lang=\"en\" dir=\"ltr\">Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.</p> ",
      "whyHtml": " <p class=\"mono\">Pourquoi on le dit ainsi</p> <p class=\"line\">« keep the focus on… » sonne plus juste dans un retour de design que le littéral « highlight the key points » ; « as-is » veut dire tel quel, et « add your own spin » est la façon native de dire improviser.</p> <p class=\"mono\">À réutiliser la prochaine fois</p> <p class=\"pair__reuse\" lang=\"en\" dir=\"ltr\"><code>keep the focus on …</code><code>use … as-is</code><code>add your own spin</code></p> ",
      "srcLabel": "Ce que vous venez d’écrire",
      "srcLine": "Supprime les éléments décoratifs, mets l’essentiel en avant, utilise les composants d’origine et n’improvise pas.",
      "outLabel": "La tournure plus naturelle en anglais",
      "outLine": "Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.",
      "ctaUrl": "",
      "ctaHtml": "",
      "whyLabel": "Pourquoi on le dit ainsi",
      "why": "« keep the focus on… » sonne plus juste dans un retour de design que le littéral « highlight the key points » ; « as-is » veut dire tel quel, et « add your own spin » est la façon native de dire improviser.",
      "reuseLabel": "À réutiliser la prochaine fois",
      "reuse": [
        "keep the focus on …",
        "use … as-is",
        "add your own spin"
      ]
    },
    "iphone": {
      "headA": "Bêta publique iPhone",
      "headB": "Synchronisé via iCloud",
      "h2": "On accumule sur le Mac, on révise sur l’iPhone.",
      "cellSrc": " <p class=\"line\">Les fiches et les favoris terminés sur le Mac arrivent automatiquement sur l’iPhone via iCloud. Loin de l’ordinateur, vous pouvez les parcourir par date, écouter l’anglais naturel et revoir ce que vous avez gardé.</p> <p><a data-hover href=\"https://testflight.apple.com/\"><span data-underline-link class=\"underline-link\">Essayer via TestFlight</span> ↗</a></p> ",
      "cellOut": " <p class=\"line\">Avant la première utilisation, activez la synchronisation iCloud dans les réglages de YiYan pour Mac et vérifiez que le Mac et l’iPhone utilisent le même compte Apple. La version iPhone reste en bêta publique et continue d’évoluer.</p> ",
      "whyHtml": "",
      "srcLabel": "",
      "srcLine": "Les fiches et les favoris terminés sur le Mac arrivent automatiquement sur l’iPhone via iCloud. Loin de l’ordinateur, vous pouvez les parcourir par date, écouter l’anglais naturel et revoir ce que vous avez gardé.",
      "outLabel": "",
      "outLine": "Avant la première utilisation, activez la synchronisation iCloud dans les réglages de YiYan pour Mac et vérifiez que le Mac et l’iPhone utilisent le même compte Apple. La version iPhone reste en bêta publique et continue d’évoluer.",
      "ctaUrl": "https://testflight.apple.com/",
      "whyLabel": "",
      "why": "",
      "reuseLabel": "",
      "reuse": []
    },
    "bounds": {
      "headA": "Les limites, dites clairement",
      "headB": "Rien que le nécessaire à l’apprentissage",
      "h2": "Seuls les messages que vous envoyez pendant son exécution.",
      "note": "YiYan ne s’installe pas dans Pi, Claude Code ou Codex et ne modifie jamais leurs réglages.",
      "items": [
        {
          "q": "Qu’est-ce qui devient une fiche ?",
          "a": "Vos messages qui disent quelque chose de complet et dont on peut réellement apprendre. Votre langue devient un anglais naturel, l’anglais est peaufiné, et le mélange des deux est réécrit en anglais complet."
        },
        {
          "q": "Qu’est-ce qui est ignoré ?",
          "a": "Les messages qui ne contiennent que du code, des chemins, des URL ou des images ; les confirmations courtes comme « ok » ou « continue » ; et les commandes brèves comme « commit and push »."
        },
        {
          "q": "Qu’est-ce qui n’est jamais conservé ?",
          "a": "Les réponses de l’IA, les sorties d’outils, les messages système, les identifiants de session et les chemins de leurs fichiers n’entrent jamais dans une fiche YiYan."
        },
        {
          "q": "Où tout cela est-il stocké ?",
          "a": "D’abord sur ce Mac. Ce n’est qu’après activation de la synchronisation iCloud que les fiches terminées et les favoris rejoignent votre iCloud puis l’iPhone. Tout ce qui ressemble à un secret est masqué avec un haut niveau de confiance avant d’entrer dans une tâche ou une fiche."
        },
        {
          "q": "Faut-il un autre modèle ?",
          "a": "Non. L’anglais naturel et les notes viennent du Pi, Claude Code ou Codex que vous veniez d’utiliser ; YiYan n’embarque ni modèle ni identifiants d’API."
        },
        {
          "q": "Quel rapport avec le reste ?",
          "a": "YiYan est une app Mac indépendante signée lazyapps. <a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">Politique de confidentialité</span></a>"
        }
      ]
    },
    "next": {
      "imgAlt": "",
      "q": "Commencez par votre prochaine phrase."
    },
    "brew": {
      "h3": "Deux lignes et c’est installé",
      "label": "Homebrew",
      "install": "<span class=\"p\">$</span> brew tap cxa/yiyan https://github.com/cxa/yiyan\n<span class=\"p\">$</span> brew install --cask cxa/yiyan/yiyan",
      "p": "Installez YiYan et continuez à utiliser Pi, Claude Code ou Codex exactement comme avant. Le prochain message dont il y a quelque chose à apprendre deviendra votre première fiche."
    },
    "footer": [
      "<a data-hover href=\"/\" lang=\"en\"><span data-underline-link class=\"underline-link\">lazyapps</span></a>",
      "<a data-hover href=\"mailto:lazyapps.feedback@gmail.com\"><span data-underline-link class=\"underline-link\">Contact</span></a>",
      "<a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">Confidentialité</span></a>",
      "<a data-hover href=\"/privacy.zh.html\" lang=\"zh\"><span data-underline-link class=\"underline-link\">中文</span></a>"
    ]
  },
  "hi": {
    "htmlLang": "hi",
    "title": "YiYan — सहज अंग्रेज़ी, काम के साथ-साथ",
    "description": "YiYan वही उठाता है जो आप Pi, Claude Code या Codex में लिखते हैं, उसका ज़्यादा सहज अंग्रेज़ी रूप देता है और बताता है कि ऐसा क्यों कहा जाता है। Mac पर जमा होता है, iCloud से iPhone तक पहुँचता है।",
    "canonical": "https://lazyapps.com/yiyan/hi/",
    "ogTitle": "YiYan — सहज अंग्रेज़ी, काम के साथ-साथ",
    "ogDesc": "YiYan वही उठाता है जो आप Pi, Claude Code या Codex में लिखते हैं, उसका ज़्यादा सहज अंग्रेज़ी रूप देता है और बताता है कि ऐसा क्यों कहा जाता है।",
    "ogUrl": "https://lazyapps.com/yiyan/hi/",
    "navAria": "मुख्य नेविगेशन",
    "homeAria": "मुख्य पृष्ठ",
    "appTitle": "YiYan",
    "appTitleAttrs": " lang=\"en\"",
    "loaderLogo": "YIYAN",
    "localeNow": "हिन्दी",
    "selectAria": "भाषा बदलें",
    "selectedUrl": "/yiyan/hi/",
    "h1": "सहज अंग्रेज़ी, काम के साथ-साथ",
    "sub": "YiYan वही उठाता है जो आप Pi, Claude Code या Codex में लिखते हैं, उसका ज़्यादा सहज अंग्रेज़ी रूप देता है और बताता है कि ऐसा क्यों कहा जाता है। Mac पर जो जमा होता है वह iCloud से iPhone पहुँच जाता है, इसलिए मेज़ से दूर भी दोहराना चलता रहता है।",
    "cta": [
      "Mac के लिए डाउनलोड",
      "iPhone सार्वजनिक बीटा",
      "अपडेट सूची देखें"
    ],
    "trust": [
      "आपका मूल अनुरोध वैसे ही जाता है",
      "अलग मॉडल या API की ज़रूरत नहीं",
      "रिकॉर्ड तारीख़ से क्रम में"
    ],
    "cssTrust": "cjk",
    "shotAltMain": "macOS पर YiYan का अध्ययन रिकॉर्ड",
    "shotAltDetail": "YiYan का एक रिकॉर्ड: मूल वाक्य, सहज अंग्रेज़ी और मुख्य नोट",
    "cards": [
      {
        "tag": "Pi · Claude Code · Codex",
        "tagLang": true,
        "title": "जैसे लिखते हैं, वैसे लिखें",
        "p": "अपनी भाषा में, अंग्रेज़ी में, या दोनों मिलाकर — सब चलेगा। आपका मूल अनुरोध पहले चला जाता है, अंग्रेज़ी के लिए रुकना नहीं पड़ता।"
      },
      {
        "tag": "चल रहा काम रुकता नहीं",
        "tagLang": false,
        "title": "असली काम चलता रहता है",
        "p": "YiYan आपके अभी भेजे अनुरोध को न बदलता है न रोकता है, और अपने नतीजे चल रही बातचीत में वापस नहीं डालता।"
      },
      {
        "tag": "अलग मॉडल या API नहीं",
        "tagLang": false,
        "title": "सहज अंग्रेज़ी, पीछे-पीछे तैयार",
        "p": "YiYan वही वाक्य उस औज़ार को देता है जिसे आप अभी इस्तेमाल कर रहे थे, और अर्थ तथा लहज़ा बचाकर संदर्भ में बैठने वाली भाषा लौटाता है।"
      },
      {
        "tag": "जो आपने असल में कहा, वही अभ्यास है",
        "tagLang": false,
        "title": "सामने रखकर सीखिए",
        "p": "आपका मूल वाक्य, सहज अंग्रेज़ी और अधिकतम तीन नोट साथ रहते हैं: क्या बदला, क्यों बेहतर लगा, अगली बार कैसे दोहराएँ।"
      }
    ],
    "pair": {
      "headA": "अपने ही लिखे से सीखिए",
      "headB": "अर्थ वही, कहन सहज",
      "h2": "समझना आसान है; अपनी बात कहना मुश्किल।",
      "cellSrc": " <p class=\"mono\">आपने अभी जो लिखा</p> <p class=\"line\">सजावटी तत्व हटा दो, ज़रूरी बात उभारो, मूल कंपोनेंट जैसे हैं वैसे इस्तेमाल करो, अपनी तरफ़ से कुछ न जोड़ो।</p> ",
      "cellOut": " <p class=\"mono\">अंग्रेज़ी में यह ज़्यादा सहज है</p> <p class=\"line\" lang=\"en\" dir=\"ltr\">Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.</p> ",
      "whyHtml": " <p class=\"mono\">ऐसा क्यों कहा जाता है</p> <p class=\"line\">डिज़ाइन पर टिप्पणी में “keep the focus on…” शब्दानुवाद “highlight the key points” से ज़्यादा जमता है; “as-is” का अर्थ है जैसा है वैसा ही रखना, और “add your own spin” अपनी तरफ़ से जोड़ने की सहज अंग्रेज़ी है।</p> <p class=\"mono\">अगली बार सीधे काम आएगा</p> <p class=\"pair__reuse\" lang=\"en\" dir=\"ltr\"><code>keep the focus on …</code><code>use … as-is</code><code>add your own spin</code></p> ",
      "srcLabel": "आपने अभी जो लिखा",
      "srcLine": "सजावटी तत्व हटा दो, ज़रूरी बात उभारो, मूल कंपोनेंट जैसे हैं वैसे इस्तेमाल करो, अपनी तरफ़ से कुछ न जोड़ो।",
      "outLabel": "अंग्रेज़ी में यह ज़्यादा सहज है",
      "outLine": "Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.",
      "ctaUrl": "",
      "ctaHtml": "",
      "whyLabel": "ऐसा क्यों कहा जाता है",
      "why": "डिज़ाइन पर टिप्पणी में “keep the focus on…” शब्दानुवाद “highlight the key points” से ज़्यादा जमता है; “as-is” का अर्थ है जैसा है वैसा ही रखना, और “add your own spin” अपनी तरफ़ से जोड़ने की सहज अंग्रेज़ी है।",
      "reuseLabel": "अगली बार सीधे काम आएगा",
      "reuse": [
        "keep the focus on …",
        "use … as-is",
        "add your own spin"
      ]
    },
    "iphone": {
      "headA": "iPhone सार्वजनिक बीटा",
      "headB": "iCloud से समन्वय",
      "h2": "Mac पर जमा कीजिए, iPhone पर दोहराइए।",
      "cellSrc": " <p class=\"line\">Mac पर पूरे हुए रिकॉर्ड और पसंदीदा iCloud के ज़रिये iPhone पर अपने आप पहुँच जाते हैं। कंप्यूटर से दूर भी आप तारीख़ से देख सकते हैं, सहज अंग्रेज़ी सुन सकते हैं और सहेजी चीज़ें दोहरा सकते हैं।</p> <p><a data-hover href=\"https://testflight.apple.com/\"><span data-underline-link class=\"underline-link\">TestFlight पर आज़माएँ</span> ↗</a></p> ",
      "cellOut": " <p class=\"line\">पहली बार से पहले Mac वाले YiYan की सेटिंग्स में iCloud समन्वय चालू करें और देख लें कि Mac और iPhone एक ही Apple खाते में हैं। iPhone वाला रूप अभी सार्वजनिक बीटा में है और सुधरता रहेगा।</p> ",
      "whyHtml": "",
      "srcLabel": "",
      "srcLine": "Mac पर पूरे हुए रिकॉर्ड और पसंदीदा iCloud के ज़रिये iPhone पर अपने आप पहुँच जाते हैं। कंप्यूटर से दूर भी आप तारीख़ से देख सकते हैं, सहज अंग्रेज़ी सुन सकते हैं और सहेजी चीज़ें दोहरा सकते हैं।",
      "outLabel": "",
      "outLine": "पहली बार से पहले Mac वाले YiYan की सेटिंग्स में iCloud समन्वय चालू करें और देख लें कि Mac और iPhone एक ही Apple खाते में हैं। iPhone वाला रूप अभी सार्वजनिक बीटा में है और सुधरता रहेगा।",
      "ctaUrl": "https://testflight.apple.com/",
      "whyLabel": "",
      "why": "",
      "reuseLabel": "",
      "reuse": []
    },
    "bounds": {
      "headA": "सीमाएँ साफ़-साफ़",
      "headB": "सीखने भर का ही रखा जाता है",
      "h2": "चलते समय आए नए संदेश ही लिए जाते हैं।",
      "note": "YiYan न Pi, Claude Code या Codex के भीतर स्थापित होता है, न उनकी सेटिंग बदलता है।",
      "items": [
        {
          "q": "रिकॉर्ड क्या बनता है?",
          "a": "आपके वे संदेश जिनमें पूरी बात है और जिनसे सचमुच सीखा जा सकता है। आपकी भाषा सहज अंग्रेज़ी बनती है, अंग्रेज़ी निखरती है, और मिली-जुली भाषा पूरी अंग्रेज़ी में लिखी जाती है।"
        },
        {
          "q": "क्या छोड़ दिया जाता है?",
          "a": "वे संदेश जिनमें केवल कोड, पथ, URL या चित्र हों; “ठीक है” या “आगे बढ़ो” जैसी छोटी पुष्टियाँ; और “commit and push” जैसे छोटे रिपॉज़िटरी आदेश।"
        },
        {
          "q": "क्या कभी सहेजा नहीं जाता?",
          "a": "AI के उत्तर, औज़ारों का आउटपुट, सिस्टम संदेश, सत्र आईडी और सत्र फ़ाइलों के पथ किसी रिकॉर्ड में नहीं जाते।"
        },
        {
          "q": "यह सब कहाँ रहता है?",
          "a": "पहले इसी Mac पर। iCloud समन्वय चालू करने के बाद ही पूरे हुए रिकॉर्ड और पसंदीदा आपके iCloud में जाते हैं और iPhone तक पहुँचते हैं। जो कुछ गुप्त कुंजी जैसा लगे, वह किसी काम या रिकॉर्ड में जाने से पहले ऊँचे भरोसे के साथ ढक दिया जाता है।"
        },
        {
          "q": "कोई और मॉडल चाहिए?",
          "a": "नहीं। सहज अंग्रेज़ी और नोट वही Pi, Claude Code या Codex बनाता है जिसे आप अभी इस्तेमाल कर रहे थे; YiYan अपना कोई मॉडल या API प्रमाण नहीं रखता।"
        },
        {
          "q": "बाकी ऐप्स से रिश्ता?",
          "a": "YiYan lazyapps का स्वतंत्र Mac ऐप है। <a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">गोपनीयता नीति</span></a>"
        }
      ]
    },
    "next": {
      "imgAlt": "",
      "q": "अगले वाक्य से शुरू कीजिए।"
    },
    "brew": {
      "h3": "दो पंक्तियों में तैयार",
      "label": "Homebrew",
      "install": "<span class=\"p\">$</span> brew tap cxa/yiyan https://github.com/cxa/yiyan\n<span class=\"p\">$</span> brew install --cask cxa/yiyan/yiyan",
      "p": "YiYan लगाइए और Pi, Claude Code या Codex पहले की तरह इस्तेमाल करते रहिए। सीखने लायक अगला संदेश ही आपका पहला रिकॉर्ड बन जाएगा।"
    },
    "footer": [
      "<a data-hover href=\"/\" lang=\"en\"><span data-underline-link class=\"underline-link\">lazyapps</span></a>",
      "<a data-hover href=\"mailto:lazyapps.feedback@gmail.com\"><span data-underline-link class=\"underline-link\">संपर्क</span></a>",
      "<a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">गोपनीयता</span></a>",
      "<a data-hover href=\"/privacy.zh.html\" lang=\"zh\"><span data-underline-link class=\"underline-link\">中文</span></a>"
    ]
  },
  "ja": {
    "htmlLang": "ja",
    "title": "YiYan — 手を止めずに、自然な英語",
    "description": "Pi、Claude Code、Codex に打ち込んだ文章をそのまま拾い、より自然な英語の言い方と、なぜそう言うのかを返します。Mac にたまった記録は iCloud で iPhone へ。",
    "canonical": "https://lazyapps.com/yiyan/ja/",
    "ogTitle": "YiYan — 手を止めずに、自然な英語",
    "ogDesc": "Pi、Claude Code、Codex に打ち込んだ文章をそのまま拾い、より自然な英語の言い方と、なぜそう言うのかを返します。",
    "ogUrl": "https://lazyapps.com/yiyan/ja/",
    "navAria": "メインナビゲーション",
    "homeAria": "ホーム",
    "appTitle": "YiYan",
    "appTitleAttrs": " lang=\"en\"",
    "loaderLogo": "YIYAN",
    "localeNow": "日本語",
    "selectAria": "言語を切り替える",
    "selectedUrl": "/yiyan/ja/",
    "h1": "手を止めずに、<wbr>自然な英語",
    "sub": "Pi、Claude Code、Codex に打ち込んだ文章をそのまま拾い、より自然な英語の言い方と、なぜそう言うのかを返します。Mac にたまった記録は iCloud で iPhone に同期され、机を離れても復習を続けられます。",
    "cta": [
      "Mac 版をダウンロード",
      "iPhone 版パブリックベータ",
      "更新履歴を見る"
    ],
    "trust": [
      "元のリクエストはそのまま送信",
      "別のモデルや API は不要",
      "学習記録は日付順に整理"
    ],
    "cssTrust": "cjk",
    "shotAltMain": "macOS 上の YiYan の学習記録画面",
    "shotAltDetail": "YiYan の学習記録 1 件：元の文、自然な英語、要点メモ",
    "cards": [
      {
        "tag": "Pi · Claude Code · Codex",
        "tagLang": true,
        "title": "いつもどおり<wbr>入力",
        "p": "母語でも英語でも、混ぜても構いません。元のリクエストが先に送られるので、英語を待つ必要はありません。"
      },
      {
        "tag": "いまの作業は中断しない",
        "tagLang": false,
        "title": "本題は<wbr>そのまま進む",
        "p": "YiYan は送ったばかりのリクエストを書き換えたり遅らせたりせず、結果を進行中の会話に差し戻すこともしません。"
      },
      {
        "tag": "別のモデルや API は不要",
        "tagLang": false,
        "title": "自然な英語を<wbr>裏で用意",
        "p": "いま使っていたツールに同じ一文を渡し、意味と語調を保ったまま、文脈に合う言い方を受け取ります。"
      },
      {
        "tag": "実際に言ったことが、そのまま練習になる",
        "tagLang": false,
        "title": "並べて<wbr>少しだけ学ぶ",
        "p": "元の文、自然な英語、最大 3 つの要点メモが並びます。どこが変わり、なぜ自然で、次にどう使い回せるか。"
      }
    ],
    "pair": {
      "headA": "自分が実際に書いた文で学ぶ",
      "headB": "意味は変えず、言い方だけ整える",
      "h2": "読めないのではなく、<wbr>自分の言葉が出てこない。",
      "cellSrc": " <p class=\"mono\">いま書いた文</p> <p class=\"line\">装飾的な要素は削って、要点を目立たせて、元のコンポーネントをそのまま使って、勝手にアレンジしないで。</p> ",
      "cellOut": " <p class=\"mono\">英語ならこう言うほうが自然</p> <p class=\"line\" lang=\"en\" dir=\"ltr\">Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.</p> ",
      "whyHtml": " <p class=\"mono\">なぜそう言うのか</p> <p class=\"line\">「keep the focus on…」は直訳の「highlight the key points」よりデザインのフィードバックに馴染みます。「as-is」はそのまま使うこと、「add your own spin」は「勝手にアレンジする」に当たる自然な言い方です。</p> <p class=\"mono\">次はそのまま使える</p> <p class=\"pair__reuse\" lang=\"en\" dir=\"ltr\"><code>keep the focus on …</code><code>use … as-is</code><code>add your own spin</code></p> ",
      "srcLabel": "いま書いた文",
      "srcLine": "装飾的な要素は削って、要点を目立たせて、元のコンポーネントをそのまま使って、勝手にアレンジしないで。",
      "outLabel": "英語ならこう言うほうが自然",
      "outLine": "Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.",
      "ctaUrl": "",
      "ctaHtml": "",
      "whyLabel": "なぜそう言うのか",
      "why": "「keep the focus on…」は直訳の「highlight the key points」よりデザインのフィードバックに馴染みます。「as-is」はそのまま使うこと、「add your own spin」は「勝手にアレンジする」に当たる自然な言い方です。",
      "reuseLabel": "次はそのまま使える",
      "reuse": [
        "keep the focus on …",
        "use … as-is",
        "add your own spin"
      ]
    },
    "iphone": {
      "headA": "iPhone 版パブリックベータ",
      "headB": "iCloud で同期",
      "h2": "Mac でためて、<wbr>iPhone で復習。",
      "cellSrc": " <p class=\"line\">Mac で仕上がった学習記録とお気に入りは、iCloud 経由で iPhone に自動同期されます。パソコンを離れても日付順に読み返し、自然な英語を聞き、保存した内容をいつでも復習できます。</p> <p><a data-hover href=\"https://testflight.apple.com/\"><span data-underline-link class=\"underline-link\">TestFlight で試す</span> ↗</a></p> ",
      "cellOut": " <p class=\"line\">初回の前に、Mac 版 YiYan の「設定」で iCloud 同期をオンにし、Mac と iPhone が同じ Apple アカウントであることを確認してください。iPhone 版はパブリックベータで、今後も改善が続きます。</p> ",
      "whyHtml": "",
      "srcLabel": "",
      "srcLine": "Mac で仕上がった学習記録とお気に入りは、iCloud 経由で iPhone に自動同期されます。パソコンを離れても日付順に読み返し、自然な英語を聞き、保存した内容をいつでも復習できます。",
      "outLabel": "",
      "outLine": "初回の前に、Mac 版 YiYan の「設定」で iCloud 同期をオンにし、Mac と iPhone が同じ Apple アカウントであることを確認してください。iPhone 版はパブリックベータで、今後も改善が続きます。",
      "ctaUrl": "https://testflight.apple.com/",
      "whyLabel": "",
      "why": "",
      "reuseLabel": "",
      "reuse": []
    },
    "bounds": {
      "headA": "境界をはっきり書く",
      "headB": "学習に必要なものだけ残す",
      "h2": "扱うのは、<wbr>動作中に届いた<wbr>新しいメッセージだけ。",
      "note": "YiYan は Pi、Claude Code、Codex の中に入り込むことはなく、それらの設定も変更しません。",
      "items": [
        {
          "q": "何が学習記録になりますか？",
          "a": "ひとまとまりの内容があり、学ぶ価値のあるあなたのメッセージです。母語は自然な英語になり、英語は磨かれ、混ざった文はきちんとした英語にまとめられます。"
        },
        {
          "q": "何が飛ばされますか？",
          "a": "コード、パス、URL、画像だけのメッセージ。「はい」「続けて」のような短い確認。そして「commit and push」のような短いリポジトリ操作です。"
        },
        {
          "q": "何が保存されませんか？",
          "a": "AI の返答、ツールの出力、システムメッセージ、セッション ID とセッションファイルのパスは、学習記録に入りません。"
        },
        {
          "q": "どこに保存されますか？",
          "a": "まずこの Mac の中です。iCloud 同期をオンにしたときだけ、仕上がった記録とお気に入りがあなたの iCloud に入り、iPhone に届きます。秘密鍵らしき文字列は、学習処理や記録に入る前に高い確度でマスクされます。"
        },
        {
          "q": "別にモデルを用意しますか？",
          "a": "不要です。自然な英語とメモは、いま使っていた Pi、Claude Code、Codex が生成します。YiYan 自身はモデルも API 認証情報も持ちません。"
        },
        {
          "q": "ほかのアプリとの関係は？",
          "a": "YiYan は lazyapps がつくる独立した Mac アプリです。<a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">プライバシーポリシー</span></a>"
        }
      ]
    },
    "next": {
      "imgAlt": "",
      "q": "次の一文から始める。"
    },
    "brew": {
      "h3": "2 行で導入",
      "label": "Homebrew",
      "install": "<span class=\"p\">$</span> brew tap cxa/yiyan https://github.com/cxa/yiyan\n<span class=\"p\">$</span> brew install --cask cxa/yiyan/yiyan",
      "p": "YiYan を入れたら、Pi、Claude Code、Codex はこれまでどおりに使ってください。次に届く学ぶ価値のあるメッセージが、最初の学習記録になります。"
    },
    "footer": [
      "<a data-hover href=\"/\" lang=\"en\"><span data-underline-link class=\"underline-link\">lazyapps</span></a>",
      "<a data-hover href=\"mailto:lazyapps.feedback@gmail.com\"><span data-underline-link class=\"underline-link\">問い合わせ</span></a>",
      "<a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">プライバシー</span></a>",
      "<a data-hover href=\"/privacy.zh.html\" lang=\"zh\"><span data-underline-link class=\"underline-link\">中文</span></a>"
    ]
  },
  "ko": {
    "htmlLang": "ko",
    "title": "YiYan — 손을 멈추지 않고, 자연스러운 영어",
    "description": "Pi, Claude Code, Codex에 입력한 문장을 그대로 받아 더 자연스러운 영어 표현과 그렇게 말하는 이유를 알려줍니다. Mac에 모인 기록은 iCloud로 iPhone까지.",
    "canonical": "https://lazyapps.com/yiyan/ko/",
    "ogTitle": "YiYan — 손을 멈추지 않고, 자연스러운 영어",
    "ogDesc": "Pi, Claude Code, Codex에 입력한 문장을 그대로 받아 더 자연스러운 영어 표현과 그렇게 말하는 이유를 알려줍니다.",
    "ogUrl": "https://lazyapps.com/yiyan/ko/",
    "navAria": "주요 내비게이션",
    "homeAria": "홈",
    "appTitle": "YiYan",
    "appTitleAttrs": " lang=\"en\"",
    "loaderLogo": "YIYAN",
    "localeNow": "한국어",
    "selectAria": "언어 변경",
    "selectedUrl": "/yiyan/ko/",
    "h1": "손을 멈추지 않고, 자연스러운 영어",
    "sub": "Pi, Claude Code, Codex에 입력한 문장을 그대로 받아 더 자연스러운 영어 표현과 그렇게 말하는 이유를 알려줍니다. Mac에 모인 기록은 iCloud로 iPhone에 동기화되어, 책상을 떠나도 복습을 이어갈 수 있습니다.",
    "cta": [
      "Mac 버전 다운로드",
      "iPhone 공개 베타",
      "업데이트 기록 보기"
    ],
    "trust": [
      "원래 요청은 그대로 전송",
      "별도의 모델이나 API 불필요",
      "학습 기록은 날짜순 정리"
    ],
    "cssTrust": "cjk",
    "shotAltMain": "macOS의 YiYan 학습 기록 화면",
    "shotAltDetail": "YiYan 학습 기록 하나: 원래 문장, 자연스러운 영어, 핵심 메모",
    "cards": [
      {
        "tag": "Pi · Claude Code · Codex",
        "tagLang": true,
        "title": "평소처럼 입력",
        "p": "모국어든 영어든 섞어 써도 괜찮습니다. 원래 요청이 먼저 전송되므로 영어를 기다릴 필요가 없습니다."
      },
      {
        "tag": "지금 하던 일은 끊기지 않음",
        "tagLang": false,
        "title": "본래 작업은 계속 진행",
        "p": "YiYan은 방금 보낸 요청을 고치거나 늦추지 않고, 결과를 진행 중인 대화에 되돌려 넣지도 않습니다."
      },
      {
        "tag": "별도의 모델이나 API 불필요",
        "tagLang": false,
        "title": "자연스러운 영어를 뒤에서 준비",
        "p": "방금 쓰던 도구에 같은 문장을 넘겨, 뜻과 말투를 지키면서 맥락에 맞는 표현을 받아옵니다."
      },
      {
        "tag": "실제로 한 말이 그대로 연습",
        "tagLang": false,
        "title": "나란히 놓고 조금씩 익히기",
        "p": "원래 문장, 자연스러운 영어, 최대 세 개의 핵심 메모가 함께 놓입니다. 무엇이 바뀌었고, 왜 더 자연스럽고, 다음에 어떻게 다시 쓸지."
      }
    ],
    "pair": {
      "headA": "내가 실제로 쓴 말로 배우기",
      "headB": "뜻은 그대로, 표현만 매끄럽게",
      "h2": "못 읽는 게 아니라, 내 말이 안 나오는 것.",
      "cellSrc": " <p class=\"mono\">방금 쓴 문장</p> <p class=\"line\">장식 요소는 빼고, 요점이 드러나게 하고, 원래 컴포넌트를 그대로 쓰고, 임의로 변형하지 마세요.</p> ",
      "cellOut": " <p class=\"mono\">영어로는 이렇게가 더 자연스럽습니다</p> <p class=\"line\" lang=\"en\" dir=\"ltr\">Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.</p> ",
      "whyHtml": " <p class=\"mono\">왜 그렇게 말하는가</p> <p class=\"line\">“keep the focus on…”은 직역인 “highlight the key points”보다 디자인 피드백에 잘 맞습니다. “as-is”는 있는 그대로 쓰라는 뜻이고, “add your own spin”은 임의로 변형한다는 말의 자연스러운 표현입니다.</p> <p class=\"mono\">다음에 바로 쓰기</p> <p class=\"pair__reuse\" lang=\"en\" dir=\"ltr\"><code>keep the focus on …</code><code>use … as-is</code><code>add your own spin</code></p> ",
      "srcLabel": "방금 쓴 문장",
      "srcLine": "장식 요소는 빼고, 요점이 드러나게 하고, 원래 컴포넌트를 그대로 쓰고, 임의로 변형하지 마세요.",
      "outLabel": "영어로는 이렇게가 더 자연스럽습니다",
      "outLine": "Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.",
      "ctaUrl": "",
      "ctaHtml": "",
      "whyLabel": "왜 그렇게 말하는가",
      "why": "“keep the focus on…”은 직역인 “highlight the key points”보다 디자인 피드백에 잘 맞습니다. “as-is”는 있는 그대로 쓰라는 뜻이고, “add your own spin”은 임의로 변형한다는 말의 자연스러운 표현입니다.",
      "reuseLabel": "다음에 바로 쓰기",
      "reuse": [
        "keep the focus on …",
        "use … as-is",
        "add your own spin"
      ]
    },
    "iphone": {
      "headA": "iPhone 공개 베타",
      "headB": "iCloud로 동기화",
      "h2": "Mac에서 모으고, iPhone에서 복습하고.",
      "cellSrc": " <p class=\"line\">Mac에서 완성된 학습 기록과 즐겨찾기는 iCloud를 통해 iPhone에 자동으로 동기화됩니다. 컴퓨터를 떠나서도 날짜순으로 다시 보고, 자연스러운 영어를 듣고, 저장한 내용을 복습할 수 있습니다.</p> <p><a data-hover href=\"https://testflight.apple.com/\"><span data-underline-link class=\"underline-link\">TestFlight로 사용해 보기</span> ↗</a></p> ",
      "cellOut": " <p class=\"line\">처음 쓰기 전에 Mac용 YiYan의 설정에서 iCloud 동기화를 켜고, Mac과 iPhone이 같은 Apple 계정으로 로그인되어 있는지 확인하세요. iPhone 버전은 아직 공개 베타이며 계속 개선됩니다.</p> ",
      "whyHtml": "",
      "srcLabel": "",
      "srcLine": "Mac에서 완성된 학습 기록과 즐겨찾기는 iCloud를 통해 iPhone에 자동으로 동기화됩니다. 컴퓨터를 떠나서도 날짜순으로 다시 보고, 자연스러운 영어를 듣고, 저장한 내용을 복습할 수 있습니다.",
      "outLabel": "",
      "outLine": "처음 쓰기 전에 Mac용 YiYan의 설정에서 iCloud 동기화를 켜고, Mac과 iPhone이 같은 Apple 계정으로 로그인되어 있는지 확인하세요. iPhone 버전은 아직 공개 베타이며 계속 개선됩니다.",
      "ctaUrl": "https://testflight.apple.com/",
      "whyLabel": "",
      "why": "",
      "reuseLabel": "",
      "reuse": []
    },
    "bounds": {
      "headA": "경계를 분명히",
      "headB": "학습에 필요한 것만 남김",
      "h2": "실행 중에 새로 보낸 메시지만 다룹니다.",
      "note": "YiYan은 Pi, Claude Code, Codex 안에 설치되지 않고, 그 설정도 바꾸지 않습니다.",
      "items": [
        {
          "q": "무엇이 학습 기록이 되나요?",
          "a": "하나의 뜻이 온전히 담겨 있고 배울 만한 내 메시지입니다. 모국어는 자연스러운 영어가 되고, 영어는 다듬어지며, 섞여 쓴 문장은 온전한 영어로 정리됩니다."
        },
        {
          "q": "무엇이 넘어가나요?",
          "a": "코드, 경로, URL, 이미지만 있는 메시지. “네”, “계속” 같은 짧은 확인. 그리고 “commit and push” 같은 짧은 저장소 명령입니다."
        },
        {
          "q": "무엇이 저장되지 않나요?",
          "a": "AI 응답, 도구 출력, 시스템 메시지, 세션 ID와 세션 파일 경로는 학습 기록에 들어가지 않습니다."
        },
        {
          "q": "어디에 보관되나요?",
          "a": "먼저 이 Mac에 저장됩니다. iCloud 동기화를 켠 뒤에야 완성된 기록과 즐겨찾기가 내 iCloud로 들어가 iPhone에 도착합니다. 비밀 키로 의심되는 값은 학습 작업과 기록에 들어가기 전에 높은 확신도로 가려집니다."
        },
        {
          "q": "모델을 따로 준비해야 하나요?",
          "a": "아닙니다. 자연스러운 영어와 메모는 방금 쓰던 Pi, Claude Code, Codex가 만듭니다. YiYan은 자체 모델도 API 자격 증명도 갖고 있지 않습니다."
        },
        {
          "q": "다른 앱과는 어떤 관계인가요?",
          "a": "YiYan은 lazyapps가 만든 독립 Mac 앱입니다. <a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">개인정보 처리방침</span></a>"
        }
      ]
    },
    "next": {
      "imgAlt": "",
      "q": "다음 문장부터 시작하세요."
    },
    "brew": {
      "h3": "두 줄로 설치",
      "label": "Homebrew",
      "install": "<span class=\"p\">$</span> brew tap cxa/yiyan https://github.com/cxa/yiyan\n<span class=\"p\">$</span> brew install --cask cxa/yiyan/yiyan",
      "p": "YiYan을 설치한 뒤에도 Pi, Claude Code, Codex는 평소처럼 쓰면 됩니다. 다음에 배울 만한 메시지가 첫 학습 기록이 됩니다."
    },
    "footer": [
      "<a data-hover href=\"/\" lang=\"en\"><span data-underline-link class=\"underline-link\">lazyapps</span></a>",
      "<a data-hover href=\"mailto:lazyapps.feedback@gmail.com\"><span data-underline-link class=\"underline-link\">문의</span></a>",
      "<a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">개인정보</span></a>",
      "<a data-hover href=\"/privacy.zh.html\" lang=\"zh\"><span data-underline-link class=\"underline-link\">中文</span></a>"
    ]
  },
  "pt-br": {
    "htmlLang": "pt-BR",
    "title": "YiYan — Inglês natural, aprendido no caminho",
    "description": "O YiYan recolhe o que você escreve no Pi, no Claude Code ou no Codex, devolve uma versão em inglês mais natural e explica por que se diz assim. Acumula no Mac e sincroniza para o iPhone pelo iCloud.",
    "canonical": "https://lazyapps.com/yiyan/pt-br/",
    "ogTitle": "YiYan — Inglês natural, aprendido no caminho",
    "ogDesc": "O YiYan recolhe o que você escreve no Pi, no Claude Code ou no Codex, devolve uma versão em inglês mais natural e explica por que se diz assim.",
    "ogUrl": "https://lazyapps.com/yiyan/pt-br/",
    "navAria": "Navegação principal",
    "homeAria": "Início",
    "appTitle": "YiYan",
    "appTitleAttrs": " lang=\"en\"",
    "loaderLogo": "YIYAN",
    "localeNow": "Português",
    "selectAria": "Mudar de idioma",
    "selectedUrl": "/yiyan/pt-br/",
    "h1": "Inglês natural, aprendido no caminho",
    "sub": "O YiYan recolhe o que você escreve no Pi, no Claude Code ou no Codex, devolve uma versão em inglês mais natural e explica por que se diz assim. O que você junta no Mac sincroniza para o iPhone pelo iCloud, para continuar revisando longe da mesa.",
    "cta": [
      "Baixar para Mac",
      "Beta pública para iPhone",
      "Notas da versão"
    ],
    "trust": [
      "Seu pedido sai como sempre",
      "Sem outro modelo ou API para configurar",
      "Registros organizados por data"
    ],
    "cssTrust": "latin",
    "shotAltMain": "O registro de aprendizado do YiYan no macOS",
    "shotAltDetail": "Um registro do YiYan: a frase original, o inglês natural e as notas principais",
    "cards": [
      {
        "tag": "Pi · Claude Code · Codex",
        "tagLang": true,
        "title": "Escreva como sempre",
        "p": "No seu idioma, em inglês ou misturando os dois — tudo serve. Seu pedido original sai primeiro, então você nunca espera pelo inglês."
      },
      {
        "tag": "Seu trabalho não é interrompido",
        "tagLang": false,
        "title": "O que importa continua rodando",
        "p": "O YiYan não reescreve nem atrasa o pedido que você acabou de enviar, e nunca joga o resultado de volta na conversa em andamento."
      },
      {
        "tag": "Sem outro modelo ou API",
        "tagLang": false,
        "title": "Uma versão natural, em segundo plano",
        "p": "O YiYan entrega a mesma frase à ferramenta que você acabou de usar e recebe uma redação que cabe no contexto, preservando sentido e tom."
      },
      {
        "tag": "O que você realmente disse é o exercício",
        "tagLang": false,
        "title": "Aprenda comparando",
        "p": "A frase original, o inglês natural e no máximo três notas ficam lado a lado: o que mudou, por que soa melhor e como reaproveitar na próxima."
      }
    ],
    "pair": {
      "headA": "Aprenda com o que você escreveu de verdade",
      "headB": "O sentido intacto, a forma mais fluida",
      "h2": "Entender é fácil; dizer do seu jeito é a parte difícil.",
      "cellSrc": " <p class=\"mono\">O que você acabou de escrever</p> <p class=\"line\">Remova os elementos decorativos, destaque o essencial, use os componentes originais e não improvise.</p> ",
      "cellOut": " <p class=\"mono\">Como soa mais natural em inglês</p> <p class=\"line\" lang=\"en\" dir=\"ltr\">Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.</p> ",
      "whyHtml": " <p class=\"mono\">Por que se diz assim</p> <p class=\"line\">“keep the focus on…” cai melhor num comentário de design do que o literal “highlight the key points”; “as-is” quer dizer usar exatamente como vem, e “add your own spin” é como um nativo chama improvisar.</p> <p class=\"mono\">Para usar na próxima</p> <p class=\"pair__reuse\" lang=\"en\" dir=\"ltr\"><code>keep the focus on …</code><code>use … as-is</code><code>add your own spin</code></p> ",
      "srcLabel": "O que você acabou de escrever",
      "srcLine": "Remova os elementos decorativos, destaque o essencial, use os componentes originais e não improvise.",
      "outLabel": "Como soa mais natural em inglês",
      "outLine": "Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.",
      "ctaUrl": "",
      "ctaHtml": "",
      "whyLabel": "Por que se diz assim",
      "why": "“keep the focus on…” cai melhor num comentário de design do que o literal “highlight the key points”; “as-is” quer dizer usar exatamente como vem, e “add your own spin” é como um nativo chama improvisar.",
      "reuseLabel": "Para usar na próxima",
      "reuse": [
        "keep the focus on …",
        "use … as-is",
        "add your own spin"
      ]
    },
    "iphone": {
      "headA": "Beta pública para iPhone",
      "headB": "Sincronizado pelo iCloud",
      "h2": "Acumule no Mac, revise no iPhone.",
      "cellSrc": " <p class=\"line\">Os registros e favoritos que você conclui no Mac chegam ao iPhone automaticamente pelo iCloud. Longe do computador, ainda é possível revê-los por data, ouvir o inglês natural e revisar o que você salvou.</p> <p><a data-hover href=\"https://testflight.apple.com/\"><span data-underline-link class=\"underline-link\">Experimente pelo TestFlight</span> ↗</a></p> ",
      "cellOut": " <p class=\"line\">Antes do primeiro uso, ative a sincronização com o iCloud nos ajustes do YiYan para Mac e confirme que Mac e iPhone usam a mesma conta Apple. A versão para iPhone segue em beta pública e continuará melhorando.</p> ",
      "whyHtml": "",
      "srcLabel": "",
      "srcLine": "Os registros e favoritos que você conclui no Mac chegam ao iPhone automaticamente pelo iCloud. Longe do computador, ainda é possível revê-los por data, ouvir o inglês natural e revisar o que você salvou.",
      "outLabel": "",
      "outLine": "Antes do primeiro uso, ative a sincronização com o iCloud nos ajustes do YiYan para Mac e confirme que Mac e iPhone usam a mesma conta Apple. A versão para iPhone segue em beta pública e continuará melhorando.",
      "ctaUrl": "https://testflight.apple.com/",
      "whyLabel": "",
      "why": "",
      "reuseLabel": "",
      "reuse": []
    },
    "bounds": {
      "headA": "Os limites, ditos com clareza",
      "headB": "Só o que o aprendizado exige",
      "h2": "Só as mensagens novas que você envia enquanto ele roda.",
      "note": "O YiYan não se instala dentro do Pi, do Claude Code ou do Codex, e nunca altera as configurações deles.",
      "items": [
        {
          "q": "O que vira registro?",
          "a": "Suas mensagens que dizem algo completo e das quais realmente se aprende. Seu idioma vira inglês natural, o inglês é lapidado e a mistura dos dois é reescrita como inglês completo."
        },
        {
          "q": "O que é ignorado?",
          "a": "Mensagens que são só código, caminhos, URLs ou imagens; confirmações curtas como “ok” ou “continue”; e comandos curtos de repositório como “commit and push”."
        },
        {
          "q": "O que nunca é guardado?",
          "a": "Respostas da IA, saída de ferramentas, mensagens de sistema, IDs de sessão e caminhos dos arquivos de sessão nunca entram num registro do YiYan."
        },
        {
          "q": "Onde tudo isso fica?",
          "a": "Primeiro neste Mac. Só depois de você ativar a sincronização com o iCloud é que os registros concluídos e os favoritos vão para o seu iCloud e chegam ao iPhone. O que parecer credencial é mascarado com alta confiança antes de entrar numa tarefa ou num registro."
        },
        {
          "q": "Preciso de outro modelo?",
          "a": "Não. O inglês natural e as notas vêm do Pi, do Claude Code ou do Codex que você acabou de usar; o YiYan não traz modelo nem credenciais de API próprias."
        },
        {
          "q": "Qual a relação com o resto?",
          "a": "O YiYan é um app de Mac independente da lazyapps. <a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">Política de privacidade</span></a>"
        }
      ]
    },
    "next": {
      "imgAlt": "",
      "q": "Comece pela sua próxima frase."
    },
    "brew": {
      "h3": "Duas linhas e pronto",
      "label": "Homebrew",
      "install": "<span class=\"p\">$</span> brew tap cxa/yiyan https://github.com/cxa/yiyan\n<span class=\"p\">$</span> brew install --cask cxa/yiyan/yiyan",
      "p": "Instale o YiYan e siga usando Pi, Claude Code ou Codex exatamente como antes. A próxima mensagem que valha aprender será seu primeiro registro."
    },
    "footer": [
      "<a data-hover href=\"/\" lang=\"en\"><span data-underline-link class=\"underline-link\">lazyapps</span></a>",
      "<a data-hover href=\"mailto:lazyapps.feedback@gmail.com\"><span data-underline-link class=\"underline-link\">Contato</span></a>",
      "<a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">Privacidade</span></a>",
      "<a data-hover href=\"/privacy.zh.html\" lang=\"zh\"><span data-underline-link class=\"underline-link\">中文</span></a>"
    ]
  },
  "ru": {
    "htmlLang": "ru",
    "title": "YiYan — естественный английский, по ходу дела",
    "description": "YiYan подхватывает то, что вы пишете в Pi, Claude Code или Codex, предлагает более естественный английский вариант и объясняет, почему так говорят. Копится на Mac, синхронизируется на iPhone через iCloud.",
    "canonical": "https://lazyapps.com/yiyan/ru/",
    "ogTitle": "YiYan — естественный английский, по ходу дела",
    "ogDesc": "YiYan подхватывает то, что вы пишете в Pi, Claude Code или Codex, предлагает более естественный английский вариант и объясняет, почему так говорят.",
    "ogUrl": "https://lazyapps.com/yiyan/ru/",
    "navAria": "Основная навигация",
    "homeAria": "Главная",
    "appTitle": "YiYan",
    "appTitleAttrs": " lang=\"en\"",
    "loaderLogo": "YIYAN",
    "localeNow": "Русский",
    "selectAria": "Сменить язык",
    "selectedUrl": "/yiyan/ru/",
    "h1": "Естественный английский, по ходу дела",
    "sub": "YiYan подхватывает то, что вы пишете в Pi, Claude Code или Codex, предлагает более естественный английский вариант и объясняет, почему так говорят. Накопленное на Mac уходит на iPhone через iCloud — повторять можно и вдали от стола.",
    "cta": [
      "Скачать для Mac",
      "Открытая бета для iPhone",
      "Список изменений"
    ],
    "trust": [
      "Исходный запрос уходит как обычно",
      "Ни второй модели, ни API",
      "Записи разложены по датам"
    ],
    "cssTrust": "latin",
    "shotAltMain": "Журнал занятий YiYan в macOS",
    "shotAltDetail": "Одна запись YiYan: исходная фраза, естественный английский и заметки",
    "cards": [
      {
        "tag": "Pi · Claude Code · Codex",
        "tagLang": true,
        "title": "Пишите как обычно",
        "p": "На своём языке, по-английски или смешивая — годится всё. Исходный запрос уходит первым, английского ждать не нужно."
      },
      {
        "tag": "Текущая работа не прерывается",
        "tagLang": false,
        "title": "Главное продолжает идти",
        "p": "YiYan не переписывает и не задерживает только что отправленный запрос и никогда не возвращает свой результат в идущий разговор."
      },
      {
        "tag": "Ни второй модели, ни API",
        "tagLang": false,
        "title": "Естественный вариант — в фоне",
        "p": "YiYan передаёт ту же фразу инструменту, которым вы только что пользовались, и получает формулировку под контекст, сохраняя смысл и тон."
      },
      {
        "tag": "Практика — то, что вы правда сказали",
        "tagLang": false,
        "title": "Учиться на сравнении",
        "p": "Исходная фраза, естественный английский и не больше трёх заметок рядом: что изменилось, почему звучит лучше, как использовать снова."
      }
    ],
    "pair": {
      "headA": "Учитесь на том, что написали сами",
      "headB": "Смысл тот же, формулировка ровнее",
      "h2": "Понять легко. Трудно сказать это своими словами.",
      "cellSrc": " <p class=\"mono\">Что вы только что написали</p> <p class=\"line\">Убери декоративные элементы, выдели главное, используй исходные компоненты и не добавляй ничего от себя.</p> ",
      "cellOut": " <p class=\"mono\">По-английски естественнее так</p> <p class=\"line\" lang=\"en\" dir=\"ltr\">Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.</p> ",
      "whyHtml": " <p class=\"mono\">Почему так говорят</p> <p class=\"line\">«keep the focus on…» звучит уместнее в отзыве о дизайне, чем буквальное «highlight the key points»; «as-is» значит взять как есть, а «add your own spin» — это и есть носительское «добавлять своё».</p> <p class=\"mono\">Пригодится в следующий раз</p> <p class=\"pair__reuse\" lang=\"en\" dir=\"ltr\"><code>keep the focus on …</code><code>use … as-is</code><code>add your own spin</code></p> ",
      "srcLabel": "Что вы только что написали",
      "srcLine": "Убери декоративные элементы, выдели главное, используй исходные компоненты и не добавляй ничего от себя.",
      "outLabel": "По-английски естественнее так",
      "outLine": "Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.",
      "ctaUrl": "",
      "ctaHtml": "",
      "whyLabel": "Почему так говорят",
      "why": "«keep the focus on…» звучит уместнее в отзыве о дизайне, чем буквальное «highlight the key points»; «as-is» значит взять как есть, а «add your own spin» — это и есть носительское «добавлять своё».",
      "reuseLabel": "Пригодится в следующий раз",
      "reuse": [
        "keep the focus on …",
        "use … as-is",
        "add your own spin"
      ]
    },
    "iphone": {
      "headA": "Открытая бета для iPhone",
      "headB": "Синхронизация через iCloud",
      "h2": "Копить на Mac, повторять на iPhone.",
      "cellSrc": " <p class=\"line\">Записи и избранное, законченные на Mac, попадают на iPhone автоматически через iCloud. Вдали от компьютера их можно листать по датам, слушать естественный английский и повторять сохранённое.</p> <p><a data-hover href=\"https://testflight.apple.com/\"><span data-underline-link class=\"underline-link\">Попробовать через TestFlight</span> ↗</a></p> ",
      "cellOut": " <p class=\"line\">Перед первым запуском включите синхронизацию с iCloud в настройках YiYan для Mac и убедитесь, что Mac и iPhone используют одну учётную запись Apple. Версия для iPhone пока в открытой бете и продолжает улучшаться.</p> ",
      "whyHtml": "",
      "srcLabel": "",
      "srcLine": "Записи и избранное, законченные на Mac, попадают на iPhone автоматически через iCloud. Вдали от компьютера их можно листать по датам, слушать естественный английский и повторять сохранённое.",
      "outLabel": "",
      "outLine": "Перед первым запуском включите синхронизацию с iCloud в настройках YiYan для Mac и убедитесь, что Mac и iPhone используют одну учётную запись Apple. Версия для iPhone пока в открытой бете и продолжает улучшаться.",
      "ctaUrl": "https://testflight.apple.com/",
      "whyLabel": "",
      "why": "",
      "reuseLabel": "",
      "reuse": []
    },
    "bounds": {
      "headA": "Границы, сказанные прямо",
      "headB": "Только то, что нужно для учёбы",
      "h2": "Только новые сообщения, отправленные при работающем приложении.",
      "note": "YiYan не устанавливается внутрь Pi, Claude Code или Codex и никогда не меняет их настройки.",
      "items": [
        {
          "q": "Что становится записью?",
          "a": "Ваши сообщения с законченной мыслью, из которых действительно есть чему учиться. Свой язык становится естественным английским, английский шлифуется, смешанное переписывается в полноценный английский."
        },
        {
          "q": "Что пропускается?",
          "a": "Сообщения только из кода, путей, URL или картинок; короткие подтверждения вроде «ок» или «продолжай»; короткие команды репозитория вроде «commit and push»."
        },
        {
          "q": "Что никогда не сохраняется?",
          "a": "Ответы ИИ, вывод инструментов, системные сообщения, идентификаторы сессий и пути к их файлам в записи YiYan не попадают."
        },
        {
          "q": "Где всё это лежит?",
          "a": "Сначала на этом Mac. Только после включения синхронизации с iCloud готовые записи и избранное уходят в ваш iCloud и на iPhone. Всё, что похоже на секрет, маскируется с высокой уверенностью до того, как попадёт в задачу или запись."
        },
        {
          "q": "Нужна ли отдельная модель?",
          "a": "Нет. Естественный английский и заметки делает тот же Pi, Claude Code или Codex, которым вы только что пользовались; у YiYan нет своей модели и своих ключей API."
        },
        {
          "q": "Как это связано с остальным?",
          "a": "YiYan — самостоятельное приложение для Mac от lazyapps. <a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">Политика конфиденциальности</span></a>"
        }
      ]
    },
    "next": {
      "imgAlt": "",
      "q": "Начните со следующей фразы."
    },
    "brew": {
      "h3": "Две строки — и готово",
      "label": "Homebrew",
      "install": "<span class=\"p\">$</span> brew tap cxa/yiyan https://github.com/cxa/yiyan\n<span class=\"p\">$</span> brew install --cask cxa/yiyan/yiyan",
      "p": "Установите YiYan и продолжайте пользоваться Pi, Claude Code или Codex как раньше. Первое же сообщение, из которого есть чему учиться, станет вашей первой записью."
    },
    "footer": [
      "<a data-hover href=\"/\" lang=\"en\"><span data-underline-link class=\"underline-link\">lazyapps</span></a>",
      "<a data-hover href=\"mailto:lazyapps.feedback@gmail.com\"><span data-underline-link class=\"underline-link\">Связаться</span></a>",
      "<a data-hover href=\"/privacy.en.html\"><span data-underline-link class=\"underline-link\">Приватность</span></a>",
      "<a data-hover href=\"/privacy.zh.html\" lang=\"zh\"><span data-underline-link class=\"underline-link\">中文</span></a>"
    ]
  },
  "zh-hant": {
    "htmlLang": "zh-Hant",
    "title": "繹言 YiYan — 地道英語，邊蹬邊學",
    "description": "自動擷取你在 Pi、Claude Code 或 Codex 裡的輸入，給出更自然的英語說法，再講清楚為什麼這樣說。Mac 上累積，透過 iCloud 同步到 iPhone。",
    "canonical": "https://lazyapps.com/yiyan/zh-hant/",
    "ogTitle": "繹言 YiYan — 地道英語，邊蹬邊學",
    "ogDesc": "自動擷取你在 Pi、Claude Code 或 Codex 裡的輸入，給出更自然的英語說法，再講清楚為什麼這樣說。",
    "ogUrl": "https://lazyapps.com/yiyan/zh-hant/",
    "navAria": "主導覽",
    "homeAria": "首頁",
    "appTitle": "<span class=\"zh\">繹言</span>",
    "appTitleAttrs": "",
    "loaderLogo": "YIYAN",
    "localeNow": "繁體中文",
    "selectAria": "切換語言",
    "selectedUrl": "/yiyan/zh-hant/",
    "h1": "<span class=\"zh\">地道英語，邊蹬邊學</span>",
    "sub": "自動擷取你在 Pi、Claude Code 或 Codex 裡的輸入，給出更自然的英語說法，再講清楚為什麼這樣說。在 Mac 上累積，透過 iCloud 同步到 iPhone，離開電腦也能繼續複習。",
    "cta": [
      "下載 Mac 版",
      "iPhone 公開測試版",
      "查看更新記錄"
    ],
    "trust": [
      "原請求照常送出",
      "無需另外設定模型或 API",
      "學習記錄依日期整理"
    ],
    "cssTrust": "cjk",
    "shotAltMain": "繹言在 macOS 上的學習記錄介面",
    "shotAltDetail": "一條繹言學習記錄：原話、自然英語與重點筆記",
    "cards": [
      {
        "tag": "Pi · Claude Code · Codex",
        "tagLang": true,
        "title": "<span class=\"zh\">照常輸入</span>",
        "p": "中文、英文、夾著說都行。你的原請求會先正常送出，不需要等英語結果。"
      },
      {
        "tag": "當前工作不被打斷",
        "tagLang": false,
        "title": "<span class=\"zh\">正事繼續執行</span>",
        "p": "繹言不會改寫或延遲當前請求，也不會把學習結果塞回正在進行的對話。"
      },
      {
        "tag": "無需另外設定模型或 API",
        "tagLang": false,
        "title": "<span class=\"zh\">背景補一版自然英語</span>",
        "p": "繹言讓你剛才使用的工具處理同一句話，在保留原意和語氣的前提下，給出一版更符合語境的說法。"
      },
      {
        "tag": "每天真的說過的話，就是練習",
        "tagLang": false,
        "title": "<span class=\"zh\">對照著學一點</span>",
        "p": "原話、自然英語和最多三條重點筆記放在一起：哪裡變了，為什麼更自然，下次還能怎麼沿用。"
      }
    ],
    "pair": {
      "headA": "拿你真的說過的話來學",
      "headB": "意思沒變，說法順了",
      "h2": "<span class=\"zh\">不是看不懂，是自己的話說不順。</span>",
      "cellSrc": " <p class=\"mono\">你剛說的</p> <p class=\"line\">去掉裝飾元素，突出重點，使用原裝元件，不要自行發揮。</p> ",
      "cellOut": " <p class=\"mono\">英語裡更自然的說法</p> <p class=\"line\" lang=\"en\" dir=\"ltr\">Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.</p> ",
      "whyHtml": " <p class=\"mono\">為什麼這樣說</p> <p class=\"line\">「keep the focus on…」比直譯的「highlight the key points」更貼近設計回饋；「as-is」表示照原樣使用，「add your own spin」則自然地表達了「自行發揮」。</p> <p class=\"mono\">下次可以直接用</p> <p class=\"pair__reuse\" lang=\"en\" dir=\"ltr\"><code>keep the focus on …</code><code>use … as-is</code><code>add your own spin</code></p> ",
      "srcLabel": "你剛說的",
      "srcLine": "去掉裝飾元素，突出重點，使用原裝元件，不要自行發揮。",
      "outLabel": "英語裡更自然的說法",
      "outLine": "Remove the decorative elements, <b>keep the focus on the content</b>, and use the original components <b>as-is</b> instead of <b>adding your own spin</b>.",
      "ctaUrl": "",
      "ctaHtml": "",
      "whyLabel": "為什麼這樣說",
      "why": "「keep the focus on…」比直譯的「highlight the key points」更貼近設計回饋；「as-is」表示照原樣使用，「add your own spin」則自然地表達了「自行發揮」。",
      "reuseLabel": "下次可以直接用",
      "reuse": [
        "keep the focus on …",
        "use … as-is",
        "add your own spin"
      ]
    },
    "iphone": {
      "headA": "iPhone 公開測試版",
      "headB": "透過 iCloud 同步",
      "h2": "<span class=\"zh\">Mac 上累積，iPhone 上複習。</span>",
      "cellSrc": " <p class=\"line\">在 Mac 上完成的學習記錄和收藏，會透過 iCloud 自動同步到 iPhone。離開電腦，也能依日期回看記錄、聽自然英語，隨時複習收藏的內容。</p> <p><a data-hover href=\"https://testflight.apple.com/\"><span data-underline-link class=\"underline-link\">透過 TestFlight 體驗</span> ↗</a></p> ",
      "cellOut": " <p class=\"line\">初次使用前，請先在 Mac 版繹言的「設定」中開啟 iCloud 同步，並確認 Mac 和 iPhone 登入同一個 Apple 帳戶。iPhone 版目前仍在公開測試，功能和體驗會繼續完善。</p> ",
      "whyHtml": "",
      "srcLabel": "",
      "srcLine": "在 Mac 上完成的學習記錄和收藏，會透過 iCloud 自動同步到 iPhone。離開電腦，也能依日期回看記錄、聽自然英語，隨時複習收藏的內容。",
      "outLabel": "",
      "outLine": "初次使用前，請先在 Mac 版繹言的「設定」中開啟 iCloud 同步，並確認 Mac 和 iPhone 登入同一個 Apple 帳戶。iPhone 版目前仍在公開測試，功能和體驗會繼續完善。",
      "ctaUrl": "https://testflight.apple.com/",
      "whyLabel": "",
      "why": "",
      "reuseLabel": "",
      "reuse": []
    },
    "bounds": {
      "headA": "邊界說清楚",
      "headB": "只留下學習所需的內容",
      "h2": "<span class=\"zh\">只處理執行期間新增的使用者訊息。</span>",
      "note": "繹言不會安裝進 Pi、Claude Code 或 Codex，也不會更改它們的設定。",
      "items": [
        {
          "q": "什麼會成為學習記錄？",
          "a": "有完整表達、確實值得學習的使用者訊息。中文會變成自然英語，英文會得到潤飾，中英混寫會整理成完整英語。"
        },
        {
          "q": "什麼會被略過？",
          "a": "只包含程式碼、路徑、URL 或圖片的訊息；「好的」「繼續」這類簡短確認；以及「commit and push」這類簡短版本庫指令。"
        },
        {
          "q": "什麼不會被保存？",
          "a": "AI 回覆、工具輸出、系統訊息、工作階段 ID 和工作階段檔案路徑，都不會寫進繹言的學習記錄。"
        },
        {
          "q": "學習內容放在哪裡？",
          "a": "首先保存在這台 Mac 上。只有在你開啟 iCloud 同步後，已完成的學習記錄與收藏才會存入你的個人 iCloud，並同步到 iPhone。疑似密鑰會在進入學習任務和記錄前先做高信賴度遮蔽。"
        },
        {
          "q": "需要再設定一套模型嗎？",
          "a": "不需要。自然英語和學習筆記由你剛才使用的 Pi、Claude Code 或 Codex 產生；繹言不帶自己的模型或 API 憑證。"
        },
        {
          "q": "和其他應用什麼關係？",
          "a": "繹言是 lazyapps 出品的獨立 Mac 應用。<a data-hover href=\"/privacy.zh.html\"><span data-underline-link class=\"underline-link\">隱私條款</span></a>"
        }
      ]
    },
    "next": {
      "imgAlt": "",
      "q": "<span class=\"zh\">從下一句話開始。</span>"
    },
    "brew": {
      "h3": "<span class=\"zh\">兩行裝好</span>",
      "label": "Homebrew",
      "install": "<span class=\"p\">$</span> brew tap cxa/yiyan https://github.com/cxa/yiyan\n<span class=\"p\">$</span> brew install --cask cxa/yiyan/yiyan",
      "p": "裝好繹言，繼續像平時一樣使用 Pi、Claude Code 或 Codex。下一條有學習價值的新訊息，會自動成為你的第一條學習記錄。"
    },
    "footer": [
      "<a data-hover href=\"/\" lang=\"en\"><span data-underline-link class=\"underline-link\">lazyapps</span></a>",
      "<a data-hover href=\"mailto:lazyapps.feedback@gmail.com\"><span data-underline-link class=\"underline-link\">聯絡</span></a>",
      "<a data-hover href=\"/privacy.zh.html\"><span data-underline-link class=\"underline-link\">隱私</span></a>",
      "<a data-hover href=\"/privacy.en.html\" lang=\"en\"><span data-underline-link class=\"underline-link\">English</span></a>"
    ]
  }
};
