"""Generate loading and unloading with the full MiniMax H3 FL2VA model."""
import argparse,hashlib,json,subprocess,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'scripts/assets/fondfont/animation/v16'
PROMPTS={
 'load':'''A refined miniature industrial stop-motion product film, one locked wide side-view camera, the two original ivory factories and orange stopped truck exactly unchanged. The small steel articulated loader in front of the LEFT type foundry handles ONE rigid wooden pallet carrying a single dense stack of varied engraved metal type blocks. This is a physically believable continuous loading shot, not a dissolve between object positions. The pallet starts on the horizontal fork platform by the left factory doorway. The steel arm raises the entire rigid pallet just above the orange truck side wall, rotates its two rigid fixed-length joints to carry the level pallet gently to the middle of the stopped truck's bed, then lowers the wooden pallet until it rests on the bed floor. The fork platform stays beneath and supports the pallet during the entire transfer. The same metal blocks remain seated, same arrangement, same sizes, no reshuffling. Truck wall naturally occludes the lower pallet once seated. Only AFTER the pallet has landed and stopped, the empty fork platform lowers slightly, withdraws horizontally and the loader folds back to its original empty resting position. Convey weight, steady controlled acceleration and real mechanical joints, restrained premium miniature craft. The right-side loader is idle. The truck stays perfectly stopped: identical cabin, wheels, body length, side wall, paint, ground contact. Factories, perspective, camera, shadows and exposure are absolutely static. No camera movement, no zoom, no cargo morphing, no disappearing goods, no scaling robot, no people, no extra vehicles, no magical teleportation. Silence.''',
 'unload':'''A refined miniature industrial stop-motion product film, one locked wide side-view camera. Preserve exactly both ivory factories and this perfectly STOPPED orange flatbed truck at the RIGHT receiving factory, unchanged cabin, wheels, paint, wheelbase and side wall. This shot is physical unloading into the dark loading bay of the large right factory. ONE rigid wooden pallet of stacked engraved metal printing type blocks starts resting in the middle of the truck bed. The small steel articulated receiving loader behind the truck first places its level support platform beneath that pallet, gently lifts the whole rigid batch JUST above the truck side wall, carries the supported pallet smoothly toward the receiving doorway behind the truck, and lowers it onto the receiving bay floor. This is a clear lift-carry-seat-withdraw sequence with believable weight. The pallet and its varied metal type blocks keep the same arrangement and actual sizes throughout, as do the fixed-length steel arm and machinery. The cabin and side wall correctly occlude machinery and goods BEHIND them. The cargo recedes into the dark bay under the same locked camera projection; it must physically pass behind the foreground cab and the doorway jamb, never shrink or dissolve to disappear. After the pallet is fully seated inside the factory, the empty support platform disengages and retracts to its original resting position. The left foundry loader stays idle. All factory walls, windows, floor and light remain precisely still. End with the orange truck empty, the whole delivered pallet resting inside the open receiving bay behind it. No moving truck, no camera pan, no zoom, no bending metal, no robot scaling, no transforming objects, no flying glyphs, no people, no new machines, no magical cargo teleportation. Silence.'''
}
def main():
 p=argparse.ArgumentParser();p.add_argument('shot',choices=PROMPTS);p.add_argument('--engine',type=Path,required=True);p.add_argument('--model',type=Path,required=True);p.add_argument('--after',choices=PROMPTS);p.add_argument('--variant',default='');p.add_argument('--resident',action='store_true',help='Same full BF16 model resident in unified memory, avoiding repeated SSD reads.');a=p.parse_args()
 if a.after:
  deadline=time.monotonic()+3600
  while True:
   previous=OUT/f'{a.after}-generation.json'
   if previous.exists() and json.loads(previous.read_text()).get('output'):break
   if time.monotonic()>deadline:raise TimeoutError('Previous H3 shot did not complete; not starting a conflicting GPU job.')
   time.sleep(3)
 suffix=('-'+a.variant) if a.variant else ''
 output=OUT/f'{a.shot}-h3{suffix}.mp4'
 if output.exists():p.error('Preserve the generated shot; make a new version for reruns.')
 text=PROMPTS[a.shot]
 if a.variant=='v2':text+=' The right factory has a clearly visible steel articulated receiving robot whose fixed pedestal is on the ground just to the RIGHT of the truck cabin. Its two long rigid steel links are connected by a large visible circular elbow joint above the cabin/bed. This EXISTING visible robot, not a hidden flying platform, must manipulate the cargo. Its elbow turns and its horizontal wrist forks slide beneath the pallet, raise the pallet only enough to clear the bed, carry it into the bay, seat it, then empty forks withdraw and return to the exact visible resting pose. Preserve this one mechanical arm and all joint connections; no machinery resizing, no unsupported floating pallet. Prioritize seeing the support link physically connected beneath the loaded fork platform.'
 prompt=OUT/f'{a.shot}-h3{suffix}-prompt.txt';prompt.write_text(text+'\n')
 inputs=[OUT/f'{a.shot}-first{suffix}.png',OUT/f'{a.shot}-last{suffix}.png',prompt]
 command=[str(a.engine.resolve()),'-d',str(a.model.resolve()),'-p',text,'--width','768','--height','480','--render-width','512','--render-height','320','--frames','89','--steps','20','--layers','50','--reuse','1','--ssd-streaming','--seed',('10071601' if a.shot=='load' else ('10071622' if a.variant else '10071602')),'--first-frame',str(inputs[0]),'--last-frame',str(inputs[1]),'--profile','-o',str(output)]
 if a.resident:command.remove('--ssd-streaming')
 metadata={'engine':'MiniMax-H3 full FL2VA checkpoint','scope':'H3 directly generates rigid cargo handling and machinery movement; no native cargo keyframes/IK in this shot. Still anchors use existing imagegen materials and real font contours.','command':command,'inputs':[{'path':str(path.relative_to(ROOT)),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()} for path in inputs]}
 (OUT/f'{a.shot}-generation{suffix}.json').write_text(json.dumps(metadata,ensure_ascii=False,indent=2)+'\n')
 with (OUT/f'{a.shot}-generation{suffix}.log').open('w') as log:subprocess.run(command,cwd=a.engine.resolve().parent,stdout=log,stderr=subprocess.STDOUT,check=True)
 metadata['output']={'path':str(output.relative_to(ROOT)),'sha256':hashlib.sha256(output.read_bytes()).hexdigest()}
 (OUT/f'{a.shot}-generation{suffix}.json').write_text(json.dumps(metadata,ensure_ascii=False,indent=2)+'\n')
 print(output,flush=True)
if __name__=='__main__':main()
